---
title: "Data preprocessing workflow"
author: "CBMR Metabolomics Platform"
date: "`r base::Sys.Date()`"

# knit: ( function(inputFile, encoding) { 
#           rmarkdown::render( inputFile, 
#                              encoding = encoding, 
#                              output_file = paste0( substr(inputFile,1,nchar(inputFile)-4), '_', Sys.Date(),'.html')) 
#           })
          
output:
  html_document:
    theme: flatly
    toc: yes
    toc_depth: '3'
    df_print: paged
---

```{r setup overall environment, include = FALSE}

wd <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(wd)
library(metpipe)
library(ggplot2)
library(openxlsx)
library(tidyverse)

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = TRUE,
  include = FALSE,
  eval = TRUE
)

```

#### Data preprocessing general input
```{r 01_input_general, include = TRUE, echo = TRUE}

params <-
  params_setup( 
    
    path.mzml = "N:/SUN-CBMR-Metabolomics/Projects/AMP_test_project/mzML/TE_LIP_MS1/",
    
    standard.name = TRUE,  # TRUE, FALSE
    
    # Metadata
    path.meta.pos = NULL,
    path.meta.neg = NULL,
    
    meta.match.col = "Sample.name", 
    
    # Library match
    rt_tolerance = 0.3,
    mz_tolerance = 0.01,
    
    # Pool samples to use for evaluation
    type.use.to.optimize = "PO100",  # For optimizing XCMS parameters
    po.sample.to.use = "PO100",      # For evaluate normalization
    
    
    ### Only modify if not standard workflow
    method = NULL,
    path.result = "N:/SUN-CBMR-Metabolomics/Projects/AMP_test_project/peaktable/TE_LIP_MS1_tar/",
    sample.pattern = ".mzML",
    
    # Library path
    #"N:/SUN-CBMR-Metabolomics/Workflow/library/
    path.lib = "N:/Documents/CBMR_workflow/packages/metpipe/inst/rmd/lib_rds/library.MS1.rds",
    path.lib.is = "N:/Documents/CBMR_workflow/packages/metpipe/inst/rmd/lib_rds/library.MS1.IS.rds",
    path.msp = "N:/SUN-CBMR-Metabolomics/Workflow/library/msdial.library.MS1.rds"

)

params$author <- "xxx (xxx@sund.ku.dk)"
```

#### 1 QC of internal standards
```{r 01_01_Preprocessing_IS, eval = TRUE}

params$mzmine.mz.tol.pos <- 0.4
params$mzmine.rt.tol.pos <- 0.01

params$mzmine.mz.tol.neg <- 0.4
params$mzmine.rt.tol.neg <- 0.01

run_module(module = "Preprocessing_IS",
           params = params)

```

```{r 01_02_QC_IS, eval = TRUE}

params$reference.type <- "reference" # reference or median
params$figure_height <- 900
params$figure_width <- 800

params$path.peaktable.IS.pos <- NULL
params$path.peaktable.IS.neg <- NULL

run_module(module = "QC_IS",
           params = params)

```

#### 2 Preprocessing
### 2.1 Targeted preprocessing
```{r 02_01_Targeted preprocessing, eval = TRUE}

params$mzmine.mz.tol.pos <- params$mz_tolerance
params$mzmine.rt.tol.pos <- params$rt_tolerance
params$mzmine.min.peaks.in.row.pos <- 1
params$mzmine.min.peaks.in.row.pos.percent <- 0

params$mzmine.mz.tol.neg <- params$mzmine.mz.tol.pos
params$mzmine.rt.tol.neg <- params$mzmine.rt.tol.pos
params$mzmine.min.peaks.in.row.neg <- params$mzmine.min.peaks.in.row.pos
params$mzmine.min.peaks.in.row.neg.percent <- params$mzmine.min.peaks.in.row.pos.percent

run_module(module = "Targeted",
           params = params)

```

### 2.2 Untargeted preprocessing - XCMS
```{r 02_02_Untargeted_preprocessing xcms, eval = FALSE}

### XCMS setup
params$para.pos <-
  list( # para.peak.picking
        max_peakwidth = 0.7*60,
        min_peakwidth = 0.1*60,
        ppm = 10,
        snthresh = 10,
        noise = 500,
        prefilter = 3,
        value_of_prefilter = 500, 
        
        # para.peak.group
        bw = 0.2*60,
        minFraction.1 = 0.5,
        minFraction.2 = 0.7,
        binSize = 0.01,
        
        # para.adjust.rt
        span = 0.6,
        minFraction.ref = 0.8,
        extraPeaks = 2
  )

params$para.neg <-
  params$para.pos

run_module(module = "Untargeted_xcms",
           params = params)

```

### 2.3 Untargeted preprocessing - MZMine
```{r 02_04_Untargeted preprocessing mzmine, eval = FALSE}

params$mzmine.mz.tol.pos <- params$mz_tolerance
params$mzmine.rt.tol.pos <- params$rt_tolerance
params$mzmine.min.peaks.in.row.pos <- 1
params$mzmine.min.peaks.in.row.pos.percent <- 0

params$mzmine.mz.tol.neg <- params$mzmine.mz.tol.pos
params$mzmine.rt.tol.neg <- params$mzmine.rt.tol.pos
params$mzmine.min.peaks.in.row.neg <- params$mzmine.min.peaks.in.row.pos
params$mzmine.min.peaks.in.row.neg.percent <- params$mzmine.min.peaks.in.row.pos.percent

run_module(module = "Untargeted_mzmine",
           params = params)

```

### 2.4 Untargeted preprocessing - msdial
```{r 02_04_Untargeted_preprocessing msdial, eval = FALSE}

params$extract_precursor <- FALSE

params$mz_tol_pos <- params$mz_tolerance
params$rt_tol_pos <- params$rt_tolerance
params$mz_tol_neg <- params$mz_tol_pos
params$rt_tol_neg <- params$rt_tol_pos

params$ri_tol <- NULL
params$ri_tol_bigger <- NULL
  
run_module(module = "Untargeted_msdial",
           params = params)

```

### 2.5 Targeted-untargeted preprocessing - xcms
```{r 02_05_Targeted-untargeted with xcms, eval = FALSE}
params$extract_precursor <- TRUE

### XCMS parameters
params$para.pos <-
  list( # para.peak.picking
        max_peakwidth = 0.6*60,
        min_peakwidth = 0.1*60,
        ppm = 10,
        snthresh = 10,
        noise = 500,
        prefilter = 3,
        value_of_prefilter = 500, 
        
        # para.peak.group
        bw = 0.2*60,
        minFraction.1 = 0.5,
        minFraction.2 = 0.7,
        binSize = 0.01,
        
        # para.adjust.rt
        span = 0.6,
        minFraction.ref = 0.8,
        extraPeaks = 2
  )

params$para.neg <-
  params$para.pos

run_module(module = "tar_untar_xcms",
           params = params)

```

### 2.6 Targeted-untargeted preprocessing - msdial
```{r 02_06_Targeted-untargeted with msdial, eval = FALSE}

params$mz_tol_pos <- params$mz_tolerance
params$rt_tol_pos <- params$rt_tolerance
params$mz_tol_neg <- params$mz_tol_pos
params$rt_tol_neg <- params$rt_tol_pos

params$ri_tol <- NULL
params$ri_tol_bigger <- NULL

params$mzmine.mz.tol.pos <- params$mz_tolerance
params$mzmine.rt.tol.pos <- params$rt_tolerance
params$mzmine.min.peaks.in.row.pos <- 1
params$mzmine.min.peaks.in.row.pos.percent <- 0

params$mzmine.mz.tol.neg <- params$mzmine.mz.tol.pos
params$mzmine.rt.tol.neg <- params$mzmine.rt.tol.pos
params$mzmine.min.peaks.in.row.neg <- params$mzmine.min.peaks.in.row.pos
params$mzmine.min.peaks.in.row.neg.percent <- params$mzmine.min.peaks.in.row.pos.percent

run_module(module = "tar_untar_msdial",
           params = params)

```

#### 3 Cleaning
```{r 03_Clean_peaktable, eval = TRUE}

### Peaktable

params$path.peaktable.pos <- NULL
params$path.peaktable.neg <- NULL

params$peaktable.sep <- ";"
params$peaktable.sample.pattern <- ".mzML Peak area"

params$mz_col_nr <- 2
params$rt_col_nr <- 3
params$identity_col_nr <- 4
params$others <- c()

### Peak cleaning setup

# Feature filtering
params$mean.filter <- list(c( 3, "BL", "<", "PO100"), # mean in PO should be > 3 times BL
                           c( 1, "PO100", ">", 500))
                           
params$rsd.filter <- c(1, "PO100", "<", 0.4)        # 0.3, RSD in PO should be < 30%
params$rt.range <- c(0.6, 30)         # c(0, 30), only keep peaks in 0 - 30 min 

# Filter based on missings
params$filter_by_missing_feature_pct <- 50

# Missing imputation
params$missing.impute.method <- "LoD"  # "LoD", "HF", "median", "min", "mean"
params$missing.is.impute.method <- "LoD"

run_module(module = "Clean",
           params = params)

```

#### 4 Normalization
```{r 04_Normalization_comparison, eval = TRUE}

### Peaktable

params$path.peaktable.pos <- NULL
params$path.peaktable.neg <- NULL

params$peaktable.sep <- ";"
params$peaktable.sample.pattern <- ".mzML Peak area"

params$mz_col_nr <- 1
params$rt_col_nr <- 2
params$identity_col_nr <- 3
params$sample_col_nr <- 4
params$others <- c()

### Processing parameters
# Filter based on missings

params$missing.sample.thres <- 30
params$missing.feature.thres <- 30

# Misssing imputation
# "LoD", "HF", "median", "min", "mean"

params$missing.impute.method.sample <- "LoD"  
params$missing.impute.method.is <- "LoD"

# Outlier removal

params$outliers.sample <- NULL
params$outliers.feature <- NULL
params$outliers.is <- NULL

# Sample types to remove from datatable
params$type.to.remove <- c("Met", "CA", "IQ", "sol", "BL")

# Normalization method
#c("bestis", "low_cv", "pqn", "nomis", "qspline", "loess", "sum", "median", "combat", "limma")

params$norm.method <- c("bestis", "low_cv", "sum", "median")

run_module(module = "Normalization",
           params = params)

```

#### 5 Merge and map info
```{r 05_Merge, eval = TRUE}

### datatables

params$path.datatable.pos <- paste0(params$path.result, "04_Normalization_comparison/", "pos_normalised_bestis.xlsx")
params$path.datatable.neg <- paste0(params$path.result, "04_Normalization_comparison/", "neg_normalised_bestis.xlsx")

params$datatable.sep <- ";"
params$feature_col_nr <- 2

run_module(module = "Merge",
           params = params)

```

```{r session info, include = FALSE}

# Session info

utils::sessionInfo()

```
