---
title: "Checking internal standards"
author: "CBMR Metabolomics Platform"
date: "`r base::Sys.Date()`"

knit: ( function(inputFile, encoding) { 
          rmarkdown::render( inputFile, 
                             encoding = encoding, 
                             output_file = paste0( substr(inputFile,1,nchar(inputFile)-4), '_', Sys.Date(),'.html')) 
          })
          
output:
  html_document:
    toc: yes
    toc_depth: '4'
    df_print: paged
  html_notebook:
    toc: yes
    toc_depth: '4'
    df_print: paged
---

```{r setup environment, include = FALSE}

if (!exists("run.pipeline")) run.pipeline <- FALSE

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  include = TRUE
)

```

```{r general setup, include = FALSE, eval = !params$run.pipeline }

source( "01_Input_general.R")
source( paste0( path.utils, "utils_qc.R" ))

```

```{r optional setup, include = FALSE, eval = !params$run.pipeline }

params$reference.type <- "reference" # reference or median
params$figure_height <- 900

params$path.peaktable.IS.pos <- NULL
params$path.peaktable.IS.neg <- NULL

params$sample.info.pos.qc <- NULL
params$sample.info.neg.qc <- NULL

```

### 1 Data import
```{r import data}

if (is.null(params$path.peaktable.IS.pos)){
  
  params$path.peaktable.IS.pos <- paste0(params$path.result, "03_01_Preprocessing_IS/peaktable_targeted_IS_pos.csv")
  print( paste0("POS peaktable for internal standards was imported from: ", params$path.peaktable.IS.pos), quote = FALSE)

}

if (is.null(params$path.peaktable.IS.neg)){
  
  params$path.peaktable.IS.neg <- paste0(params$path.result, "03_01_Preprocessing_IS/peaktable_targeted_IS_neg.csv")
  print( paste0("NEG peaktable for internal standards was imported from: ", params$path.peaktable.IS.neg), quote = FALSE)

}

if (is.null(params$sample.info.pos.qc)){
  params$sample.info.pos.qc <- params$sample.info.pos
}

if (is.null(params$sample.info.neg.qc)){
  params$sample.info.neg.qc <- params$sample.info.neg
}



```

### 2 POS Overview {.tabset}

```{r evaluation pos, include = FALSE, eval = params$run.pos}

# Extract theoretical and actual internal standard
combined_file <-
  extract.is( sample.info = params$sample.info.pos.qc,
              reference.type = params$reference.type,
              lib.istd = params$lib.is[[params$method]]$pos,
              path.peaktable.IS = params$path.peaktable.IS.pos,
              path.result = params$path.result)

plt <- create.qc(sampled_data = combined_file,
                 figure_height = params$figure_height)

summary <- 
  combined_file %>%
  select(ISTD, Theoretical.rt, median.rt, Theoretical.mz, median.mz, median.intensity, RSD.intensity) %>%
  unique()

```

#### Overall
```{r ms overall pos, eval = params$run.pos}

knitr::kable(summary)

plt[[7]] %>%
  layout(annotations = list(
          list(x = 0,  
               y = 1.0,  
               text = "RSD of internal standards",  
               xref = "paper",  
               yref = "paper",  
               xanchor = "left",  
               yanchor = "bottom",  
               showarrow = FALSE)
        ))

plt[[8]] %>%
  layout(annotations = list(
          list(x = 0,  
               y = 1.0,  
               text = "Retention time linearity of internal standards",  
               xref = "paper",  
               yref = "paper",  
               xanchor = "left",  
               yanchor = "bottom",  
               showarrow = FALSE)
        ))

```

#### Retention time
```{r ms RT pos, eval = params$run.pos}

subplot(plt[[1]], plt[[2]], nrows = 2, margin = 0.04, titleX = TRUE, titleY = TRUE) 

```

#### m/z
```{r ms m/z pos, eval = params$run.pos}

subplot(plt[[3]], plt[[4]], nrows = 2, margin = 0.04, titleX = TRUE, titleY = TRUE) 

```

#### Intensity
```{r ms1p Int pos, eval = params$run.pos}

subplot(plt[[5]], plt[[6]], nrows = 2, margin = 0.04, titleX = TRUE, titleY = TRUE) 

```


### 3 NEG Overview {.tabset}
```{r evaluation neg, include = FALSE, eval = params$run.neg}

# Extract theoretical and actual internal standard
combined_file <-
  extract.is( sample.info = params$sample.info.neg.qc,
              reference.type = params$reference.type,
              lib.istd = params$lib.is[[params$method]]$neg,
              path.peaktable.IS = params$path.peaktable.IS.neg,
              path.result = params$path.result)

plt <- metpipe::create.qc(sampled_data = combined_file,
                 figure_height = params$figure_height)

summary <- 
  combined_file %>%
  select(ISTD, Theoretical.rt, median.rt, Theoretical.mz, median.mz, median.intensity, RSD.intensity) %>%
  unique()

```

#### Overall
```{r ms overall neg, eval = params$run.neg}

knitr::kable(summary)

plt[[7]] %>%
  layout(annotations = list(
          list(x = 0,  
               y = 1.0,  
               text = "RSD of internal standards",  
               xref = "paper",  
               yref = "paper",  
               xanchor = "left",  
               yanchor = "bottom",  
               showarrow = FALSE)
        ))

plt[[8]] %>%
  layout(annotations = list(
          list(x = 0,  
               y = 1.0,  
               text = "Retention time linearity of internal standards",  
               xref = "paper",  
               yref = "paper",  
               xanchor = "left",  
               yanchor = "bottom",  
               showarrow = FALSE)
        ))

```

#### Retention time
```{r ms RT neg, eval = params$run.neg}

subplot(plt[[1]], plt[[2]], nrows = 2, margin = 0.04, titleX = TRUE, titleY = TRUE) 

```

#### m/z
```{r ms m/z neg, eval = params$run.neg}

subplot(plt[[3]], plt[[4]], nrows = 2, margin = 0.04, titleX = TRUE, titleY = TRUE) 

```

#### Intensity
```{r ms1p Int neg, eval = params$run.neg}

subplot(plt[[5]], plt[[6]], nrows = 2, margin = 0.04, titleX = TRUE, titleY = TRUE) 

```
