---
title: "Clean peaktable"
author: "CBMR Metabolomics Platform"
date: "`r base::Sys.Date()`"

knit: ( function(inputFile, encoding) { 
          rmarkdown::render( inputFile, 
                             encoding = encoding, 
                             output_file = paste0( substr(inputFile,1,nchar(inputFile)-4), '_', Sys.Date(),'.html')) 
          })

output:
  html_document:
    toc: yes
    toc_depth: '4'
    df_print: paged
  html_notebook:
    toc: yes
    toc_depth: '4'
    df_print: paged
---

```{r setup environment, include = FALSE}

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  include = TRUE
)

```

```{r set path, include = FALSE}

path.output <-
  paste0(params$path.result, "05_Clean_peaktable/")

if (!dir.exists(path.output)) dir.create(path.output)

if (is.null(params$path.peaktable.pos) | is.null(params$path.peaktable.neg)){

  params$mz_col_nr <- 2
  params$rt_col_nr <- 3
  params$identity_col_nr <- 4
  
}

if (is.null(params$path.peaktable.pos)){
  
  params$path.peaktable.pos <- paste0(params$path.result, "04_Preprocessing/peaktable_targeted_pos.csv")
  
} 

if (is.null(params$path.peaktable.neg)){
  
  params$path.peaktable.neg <- paste0(params$path.result, "04_Preprocessing/peaktable_targeted_neg.csv")
  
} 

```

### POS
#### 1 Data import
```{r data import pos, eval = params$run.pos}

if ( grepl(".xlsx", params$path.peaktable.pos) ){
  
  peaktable <-
    readxl::read_excel( params$path.peaktable.pos )
  
} else if (is.data.frame(params$path.peaktable.pos)){
  
  peaktable <- params$path.peaktable.pos
  
} else {
  
  peaktable <-
    read.csv( params$path.peaktable.pos, 
              sep = params$peaktable.sep, 
              check.names = FALSE)
  
}

print("POS peaktable was imported from the following file:", quote = FALSE)
print(params$path.peaktable.pos, quote = FALSE)

peaks.names <-
  paste0(params$sample.info.pos$Sample.name, params$peaktable.sample.pattern)
 
peaks.all <-
  cbind(peaktable[, c(params$mz_col_nr, params$rt_col_nr, params$identity_col_nr)], peaktable[, peaks.names])

f.info <- 
  peaktable[, c(params$identity_col_nr, params$others), drop = FALSE] %>%
  dplyr::rename( Identity = 1) %>%
  mutate(  Identity = if_else( grepl(": 0.", Identity, fixed = TRUE),
                               substr(Identity, 1, regexpr("\\:[^\\:]*$", Identity)-1),
                               Identity),
           Identity = ifelse( is.na(Identity),
                             paste0(round(mz, 3), "_", round(rt, 3)),
                             Identity ),
          Feature.id = row_number()) %>%
  group_by(Identity) %>%
  mutate( n = n(), 
          Identity = ifelse( n > 1, 
                             paste0(Identity, "-iso", row_number()),
                             Identity)) %>%
  ungroup() %>%
  arrange(Feature.id) %>%
  select( -c(n, Feature.id) )

peaks.temp <-
  peaks.all %>%
  dplyr::rename( mz = 1,
                 rt = 2,
                 Identity = 3) %>%
  mutate(  Identity = if_else( grepl(": 0.", Identity, fixed = TRUE),
                               substr(Identity, 1, regexpr("\\:[^\\:]*$", Identity)-1),
                               Identity),
           Identity = ifelse( is.na(Identity),
                             paste0(round(mz, 3), "_", round(rt, 3)),
                             Identity ),
          Feature.id = row_number()) %>%
  group_by(Identity) %>%
  mutate( n = n(), 
          Identity = ifelse( n > 1, 
                             paste0(Identity, "-iso", row_number()),
                             Identity)) %>%
  ungroup() %>%
  arrange(Feature.id) %>%
  select( -c(n, Feature.id) )

peaks.is <-
  peaks.temp %>%
  filter(substr(Identity, 3, 3) == ".")

peaks <-
  peaks.temp %>%
  filter(substr(Identity, 3, 3) != ".")
  
```


#### 2 Feature filtering
```{r filtering, eval = params$run.pos}

# Peaks
mzrt.filtered <-
  filter_peaks( peaktable = peaks,
                sample.type = params$sample.info.pos$Sample.type,
                bl.thres = params$bl.thres,
                rsd.po.thres = params$rsd.po.thres,
                mean.po.thres = params$mean.po.thres,
                rt.range = params$rt.range,
                mean.thres = params$mean.thres)

peaks.filtered <- 
  mzrt.filtered$peaktable


features <- 
  cbind( peaks.filtered[, c("mz", "rt", "Identity")], mzrt.filtered$summary[, -1])

data <- 
  t(peaks.filtered[, !colnames(peaks.filtered) %in% c("mz", "rt", "Identity")]) %>%
  as.data.frame()

colnames(data) <- features$Identity

# IS
mzrt.is.filtered <-
  filter_peaks( peaktable = peaks.is,
                sample.type = params$sample.info.pos$Sample.type,
                bl.thres = c(),
                rsd.po.thres = params$rsd.po.thres,
                mean.po.thres = params$mean.po.thres,
                rt.range = params$rt.range,
                mean.thres = c())

peaks.is.filtered <- 
  mzrt.is.filtered$peaktable


features.is <- 
  cbind( peaks.is.filtered[, c("mz", "rt", "Identity")], mzrt.is.filtered$summary[, -1])

data.is <- 
  t(peaks.is.filtered[, !colnames(peaks.is.filtered) %in% c("mz", "rt", "Identity")]) %>%
  as.data.frame()

colnames(data.is) <- features.is$Identity

```


#### 3 Filter based on missings
```{r filter, eval = params$run.pos}

# By feature
feature_filter <- 
  filter_by_missing( data, 
                     method = 'feature',                        #feature or sample
                     threshold = params$filter_by_missing_feature_pct  #Percentage
  )

data <- feature_filter$x
features <- 
  features[feature_filter$index, ] %>%
  left_join(f.info, by = "Identity")


# IS by feature
feature_filter.is <- 
  filter_by_missing( data.is, 
                     method = 'feature',                        #feature or sample
                     threshold = params$filter_by_missing_feature_pct  #Percentage
  )

data.is <- feature_filter.is$x
features.is <- 
  features.is[feature_filter.is$index, ] %>%
  left_join(f.info, by = "Identity")

```

#### 4 Missing imputation
```{r impute, eval = params$run.pos}

# Peaks
data.impute <- 
  impute_various_methods( data,
                          method = params$missing.impute.method
  )

data <- data.impute$x

# IS
data.impute.is <- 
  impute_various_methods( data.is,
                          method = params$missing.impute.method
  )

data.is <- data.impute.is$x

```

#### 5 Remove duplicate internal standard
```{r remove dup is, eval = params$run.pos}

features.is.keep <-
  features.is %>%
  rowwise() %>%
  mutate(Identity_new = strsplit(Identity, "-iso")[[1]][1]) %>%
  group_by(Identity_new) %>%
  arrange(Identity_new, desc(get(paste0("mean.", params$po.sample.to.use)))) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  select(-Identity_new)

data.is.keep <-
  data.is[, features.is.keep$Identity]

```

```{r export, eval = params$run.pos}

### Prepare feature info

peaktable.cleaned <-
  cbind( features[, c("mz", "rt", "Identity", names(f.info)[-1])], 
         t(data)) %>%
  rowwise() %>% 
  mutate( Identity = strsplit( Identity, "-iso")[[1]][1] ) %>%
  group_by(Identity) %>%
  mutate( n = n(), 
          Identity = ifelse( n > 1, 
                             paste0(Identity, "-iso", row_number()),
                             Identity)) %>%
  ungroup() %>%
  select( -n )

peaktable.is.cleaned <-
  cbind( features.is.keep[, c("mz", "rt", "Identity", names(f.info)[-1])], 
         t(data.is.keep)) %>%
  rowwise() %>% 
  mutate( Identity = strsplit( Identity, "-iso")[[1]][1] ) %>%
  group_by(Identity) %>%
  mutate( n = n(), 
          Identity = ifelse( n > 1, 
                             paste0(Identity, "-iso", row_number()),
                             Identity)) %>%
  ungroup() %>%
  select( -n )

features$Identity_orig <- features$Identity
features$Identity <- peaktable.cleaned$Identity

features.is.keep$Identity_orig <- features.is.keep$Identity
features.is.keep$Identity <- peaktable.is.cleaned$Identity

peaktable.cleaned <-
  bind_rows(peaktable.cleaned, peaktable.is.cleaned)
        
output.file <- paste0(path.output, "peaktable_targeted_pos_cleaned.xlsx")

features.cleaned <-
  bind_rows(features, features.is.keep)
  
wb <- createWorkbook()
addWorksheet(wb, "peaktable")
writeData(wb, "peaktable", peaktable.cleaned)
addWorksheet(wb, "features")
writeData(wb, "features", features.cleaned)
saveWorkbook(wb, file = output.file, overwrite = TRUE)

print( paste0("POS cleaned peaktable was saved as: ", output.file ), quote = FALSE)

```

### NEG
#### 1 Data import
```{r data import neg, eval = params$run.neg}

if ( grepl(".xlsx", params$path.peaktable.neg) ){
  
  peaktable <-
    readxl::read_excel( params$path.peaktable.neg )
  
} else if (is.data.frame(params$path.peaktable.neg)){
  
  peaktable <- params$path.peaktable.neg
  
} else {
  
  peaktable <-
    read.csv( params$path.peaktable.neg, 
              sep = params$peaktable.sep, 
              check.names = FALSE)
  
}

print("NEG peaktable was imported from the following file:", quote = FALSE)
print(params$path.peaktable.neg, quote = FALSE)

peaks.names <-
  paste0(params$sample.info.neg$Sample.name, params$peaktable.sample.pattern)
  
peaks.all <-
  cbind(peaktable[, c(params$mz_col_nr, params$rt_col_nr, params$identity_col_nr)], peaktable[, peaks.names])

f.info <- 
  peaktable[, c(params$identity_col_nr, params$others), drop = FALSE] %>%
  dplyr::rename( Identity = 1) %>%
  mutate(  Identity = if_else( grepl(": 0.", Identity, fixed = TRUE),
                               substr(Identity, 1, regexpr("\\:[^\\:]*$", Identity)-1),
                               Identity),
           Identity = ifelse( is.na(Identity),
                             paste0(round(mz, 3), "_", round(rt, 3)),
                             Identity ),
          Feature.id = row_number()) %>%
  group_by(Identity) %>%
  mutate( n = n(), 
          Identity = ifelse( n > 1, 
                             paste0(Identity, "-iso", row_number()),
                             Identity)) %>%
  ungroup() %>%
  arrange(Feature.id) %>%
  select( -c(n, Feature.id) )

peaks.temp <-
  peaks.all %>%
  dplyr::rename( mz = 1,
                 rt = 2,
                 Identity = 3) %>%
  mutate( Identity = if_else( grepl(": 0.", Identity, fixed = TRUE),
                               substr(Identity, 1, regexpr("\\:[^\\:]*$", Identity)-1),
                               Identity),
          Identity = ifelse( is.na(Identity),
                             paste0(round(mz, 3), "_", round(rt, 3)),
                             Identity ),
          Feature.id = row_number()) %>%
  group_by(Identity) %>%
  mutate( n = n(), 
          Identity = ifelse( n > 1, 
                             paste0(Identity, "-iso", row_number()),
                             Identity)) %>%
  ungroup() %>%
  arrange(Feature.id) %>%
  select( -c(n, Feature.id) )

peaks.is <-
  peaks.temp %>%
  filter(substr(Identity, 3, 3) == ".")

peaks <-
  peaks.temp %>%
  filter(substr(Identity, 3, 3) != ".")

```


#### 2 Feature filtering
```{r filtering neg, eval = params$run.neg}

# Peaks
mzrt.filtered <-
  filter_peaks( peaktable = peaks,
                sample.type = params$sample.info.neg$Sample.type,
                bl.thres = params$bl.thres,
                rsd.po.thres = params$rsd.po.thres,
                mean.po.thres = params$mean.po.thres,
                rt.range = params$rt.range,
                mean.thres = params$mean.thres)

peaks.filtered <- 
  mzrt.filtered$peaktable


features <- 
  cbind( peaks.filtered[, c("mz", "rt", "Identity")], mzrt.filtered$summary[, -1])

data <- 
  t(peaks.filtered[, !colnames(peaks.filtered) %in% c("mz", "rt", "Identity")]) %>%
  as.data.frame()

colnames(data) <- features$Identity

# IS
mzrt.is.filtered <-
  filter_peaks( peaktable = peaks.is,
                sample.type = params$sample.info.neg$Sample.type,
                bl.thres = c(),
                rsd.po.thres = params$rsd.po.thres,
                mean.po.thres = params$mean.po.thres,
                rt.range = params$rt.range,
                mean.thres = c())

peaks.is.filtered <- 
  mzrt.is.filtered$peaktable


features.is <- 
  cbind( peaks.is.filtered[, c("mz", "rt", "Identity")], mzrt.is.filtered$summary[, -1])

data.is <- 
  t(peaks.is.filtered[, !colnames(peaks.is.filtered) %in% c("mz", "rt", "Identity")]) %>%
  as.data.frame()

colnames(data.is) <- features.is$Identity

```


#### 3 Filter based on missings
```{r filter neg, eval = params$run.neg}

# By feature
feature_filter <- 
  filter_by_missing( data, 
                     method = 'feature',                        #feature or sample
                     threshold = params$filter_by_missing_feature_pct  #Percentage
  )

data <- feature_filter$x
features <- 
  features[feature_filter$index, ] %>%
  left_join(f.info, by = "Identity")

# IS by feature
feature_filter.is <- 
  filter_by_missing( data.is, 
                     method = 'feature',                        #feature or sample
                     threshold = params$filter_by_missing_feature_pct  #Percentage
  )

data.is <- feature_filter.is$x
features.is <- 
  features.is[feature_filter.is$index, ] %>%
  left_join(f.info, by = "Identity")

```

#### 4 Missing imputation
```{r impute neg, eval = params$run.neg}

# Peaks
data.impute <- 
  impute_various_methods( data,
                          method = params$missing.impute.method
  )

data <- data.impute$x

# IS
data.impute.is <- 
  impute_various_methods( data.is,
                          method = params$missing.impute.method
  )

data.is <- data.impute.is$x

```

#### 5 Remove duplicate internal standard
```{r remove dup is neg, eval = params$run.pos}

features.is.keep <-
  features.is %>%
  rowwise() %>%
  mutate(Identity_new = strsplit(Identity, "-iso")[[1]][1]) %>%
  group_by(Identity_new) %>%
  arrange(Identity_new, desc(get(paste0("mean.", params$po.sample.to.use)))) %>%
  filter(row_number() == 1) %>%
  ungroup() %>%
  select(-Identity_new)

data.is.keep <-
  data.is[, features.is.keep$Identity]

```

```{r export neg, eval = params$run.neg}

### Prepare feature info

peaktable.cleaned <-
  cbind( features[, c("mz", "rt", "Identity", names(f.info)[-1]),], 
         t(data)) %>%
  rowwise() %>% 
  mutate( Identity = strsplit( Identity, "-iso")[[1]][1] ) %>%
  group_by(Identity) %>%
  mutate( n = n(), 
          Identity = ifelse( n > 1, 
                             paste0(Identity, "-iso", row_number()),
                             Identity)) %>%
  ungroup() %>%
  select( -n )

peaktable.is.cleaned <-
  cbind( features.is.keep[, c("mz", "rt", "Identity", names(f.info)[-1])], 
         t(data.is.keep)) %>%
  rowwise() %>% 
  mutate( Identity = strsplit( Identity, "-iso")[[1]][1] ) %>%
  group_by(Identity) %>%
  mutate( n = n(), 
          Identity = ifelse( n > 1, 
                             paste0(Identity, "-iso", row_number()),
                             Identity)) %>%
  ungroup() %>%
  select( -n )

features$Identity_orig <- features$Identity
features$Identity <- peaktable.cleaned$Identity

features.is.keep$Identity_orig <- features.is.keep$Identity
features.is.keep$Identity <- peaktable.is.cleaned$Identity

peaktable.cleaned <-
  bind_rows(peaktable.cleaned, peaktable.is.cleaned)

output.file <- paste0(path.output, "peaktable_targeted_neg_cleaned.xlsx")
  
features.cleaned <-
  bind_rows(features, features.is.keep)

wb <- createWorkbook()
addWorksheet(wb, "peaktable")
writeData(wb, "peaktable", peaktable.cleaned)
addWorksheet(wb, "features")
writeData(wb, "features", features.cleaned)
saveWorkbook(wb, file = output.file, overwrite = TRUE)

print( paste0("NEG cleaned peaktable was saved as: ", output.file ), quote = FALSE)
```
