---
title: "Data preprocessing workflow"
author: "CBMR Metabolomics Platform"
date: "`r base::Sys.Date()`"
          
output:
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: false
    toc_depth: '4'
    df_print: paged
---

<style type="text/css">
body{
  font-size: 12px;
  }
td {
  font-size: 14px;
}
h1.title {
  font-size: 22px;
}
h4.author {
  font-size: 16px;
}
h4.date {
  font-size: 16px;
}

h1 {
  font-size: 18px;
}
h2 {
  font-size: 16px;
}
h3 {
  font-size: 14px;
}
h4 {
  font-size: 12px;
}
h5 {
  font-size: 12px;
}
code.r{
  font-size: 12px;
}
pre {
  font-size: 14px;
}
</style>

```{r setup overall environment, include = FALSE}

library(metpipe)
library(tidyverse)

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = TRUE,
  include = FALSE,
  eval = TRUE
)

```

# Data preprocessing general input
```{r 01_input_general, include = TRUE, echo = TRUE}

params <-
  params_setup( 
    
    path.mzml = "N:/SUN-CBMR-Metabolomics/Projects/AMP_test_project/mzML/EX_LIP_MS1/",
    
    standard.name = FALSE,  # TRUE, FALSE
    
    # Metadata
    path.meta.pos = "N:/SUN-CBMR-Metabolomics/Projects/AMP_test_project/files/meta/EX_LIP_meta_pos.xlsx",
    path.meta.neg = "N:/SUN-CBMR-Metabolomics/Projects/AMP_test_project/files/meta/EX_LIP_meta_neg.xlsx",
    
    meta.match.col = "Sample.name", 
    
    # Library match
    rt_tolerance = 0.3,
    mz_tolerance = 0.01,
    
    # Pool samples to use for evaluation
    po.sample.to.use = "PO",      # For evaluate normalization
    
    ### Only modify if not standard workflow
    method = NULL,
    path.result = "N:/SUN-CBMR-Metabolomics/Projects/AMP_test_project/peaktable/EX_LIP_tar_skyline/",
    sample.pattern = ".mzML",
    
    # Library path
    path.lib = "N:/SUN-CBMR-Metabolomics/Workflow/library/library.MS1.rds",
    path.lib.is = "N:/SUN-CBMR-Metabolomics/Workflow/library/library.MS1.IS.rds",
    path.msp = "N:/SUN-CBMR-Metabolomics/Workflow/library/msdial.library.MS1.rds",
    
    author = "xxx (xxx@sund.ku.dk)"

)

```

# Formatting
```{r}
params$run.neg <- FALSE

convert_skyline_data(
    file = NULL,
    mode = NULL,
    path.result = NULL)!!!! continue

    
raw <- 
  read.csv("LIP_Molecule Transition Results.csv", sep = ",") %>% 
  mutate(rt = 1,
         Replicate.Name = paste0(Replicate.Name, ".mzML"),
         Area = as.numeric(Area),
         Area = if_else(is.na(Area), 0, Area)) %>% 
  filter(Fragment.Ion == "precursor") %>% 
  filter(Peak.Rank %in% c("1", "2")) %>% 
  select(-c("Precursor.Adduct", "Precursor.Charge", "Fragment.Ion", "Product.Adduct", 
            "Product.Charge", "Background", "Peak.Rank")) %>%
  dplyr::rename("Feature m/z" = "Product.Mz",
                "Feature RT" = "Retention.Time",
                "Peak area" = "Area") %>% 
  pivot_wider(names_from = Replicate.Name, 
              values_from = c("Feature m/z", "Feature RT", "Peak area"),
              names_glue = "{Replicate.Name} {.value}") %>% 
  group_by(Molecule) %>% 
  filter(row_number() == 1) %>%
  dplyr::rename("row retention time" = "rt",
                "row m/z" = "Precursor.Mz",
                "row identity (main ID)" = "Molecule") %>% 
  relocate(c("row m/z", "row retention time", "row identity (main ID)"), .after = "Molecule.List.Name")

raw_is <- 
  raw %>% 
  filter(Molecule.List.Name == "IS") %>% 
  select(-Molecule.List.Name) %>% 
  mutate(ID = row_number()) %>% 
  relocate(ID, .before = "row m/z")
  
raw_peak <- 
  raw %>% 
  select(-Molecule.List.Name) %>% 
  mutate(ID = row_number()) %>% 
  relocate(ID, .before = "row m/z")

keep_names <- !grepl(" Feature m/z| Feature RT", names(raw_peak))
raw_peak <- raw_peak[, keep_names]

dir.create(paste0(params$path.result, "/01_01_Preprocessing_IS/"))
write.table(raw_is, sep = ";", row.names = FALSE,
            file = paste0(params$path.result, "01_01_Preprocessing_IS/peaktable_targeted_IS_pos.csv"))

dir.create(paste0(params$path.result, "/02_Preprocessing/"))
write.table(raw_peak, sep = ";", row.names = FALSE,
            file = paste0(params$path.result, "02_Preprocessing/peaktable_pos.csv"))
```


# 1 QC of internal standards
```{r 01_01_Preprocessing_IS, eval = TRUE}

params$mzmine.mz.tol.pos <- 0.01
params$mzmine.rt.tol.pos <- 0.4

params$mzmine.mz.tol.neg <- 0.01
params$mzmine.rt.tol.neg <- 0.4

run_module(module = "Preprocessing_IS",
           params = params)

```

```{r 01_02_QC_IS, eval = TRUE}

params$reference.type <- "reference" # reference or median

run_module(module = "QC_IS",
           params = params)

params$sample.info.pos.qc <- NULL
params$sample.info.neg.qc <- NULL

render_rmarkdown(
  # file = ifelse(is.null(file),
  #                system.file("rmd", "QC_IS_other.Rmd", package="metpipe"),
  #                file),
  file = "H:/Documents/CBMR_workflow/packages/metpipe/inst/rmd/QC_IS_other.Rmd",
  params = params,
  output = paste0( params$path.result, '01_02_QC_IS')
  )
```

# 2 Targeted preprocessing - mzmine
```{r 02_01_Targeted preprocessing, eval = TRUE}

params$mzmine.mz.tol.pos <- 0.01
params$mzmine.rt.tol.pos <- 0.3
params$mzmine.min.peaks.in.row.pos <- 1

params$mzmine.mz.tol.neg <- 0.01
params$mzmine.rt.tol.neg <- 0.3
params$mzmine.min.peaks.in.row.neg <- params$mzmine.min.peaks.in.row.pos

run_module(module = "Targeted",
           params = params)

```

# 3 Cleaning
```{r 03_Clean_peaktable, eval = TRUE}

### Peaktable

params$path.peaktable.pos <- NULL
params$path.peaktable.neg <- NULL

params$peaktable.sep <- ";"
params$peaktable.sample.pattern <- ".mzML Peak area"

params$mz_col_nr <- 2
params$rt_col_nr <- 3
params$identity_col_nr <- 4
params$others <- c()

### Peak cleaning setup

# Feature filtering
params$mean.filter <- list(c( 3, "BL", "<", "PO"), # mean in PO should be > 3 times BL
                           c( 1, "PO", ">", 100*60))
                           
params$rsd.filter <- c(1, "PO", "<", 0.3)        # 0.3, RSD in PO should be < 30%
#params$rsd.filter <- c(1.5, "PO", "<", "Sample")        

params$rt.range <- c(0.6, 30)         # c(0, 30), only keep peaks in 0 - 30 min 

# Filter based on missings
params$filter_by_missing_feature_pct <- 50

run_module(module = "Clean",
           params = params)

```

# 4 Normalization
```{r 04_Normalization_comparison, eval = TRUE}

### Peaktable

params$path.peaktable.pos <- NULL
params$path.peaktable.neg <- NULL

params$peaktable.sep <- ";"
params$peaktable.sample.pattern <- ".mzML Peak area"

params$mz_col_nr <- 1
params$rt_col_nr <- 2
params$identity_col_nr <- 3
params$sample_col_nr <- 4
params$others <- c()

### Processing parameters
# Filter based on missings

params$missing.sample.thres <- 30
params$missing.feature.thres <- 30

# Misssing imputation
# "LoD", "HF", "median", "min", "mean"

params$missing.impute.method.sample <- "HF"  
params$missing.impute.method.is <- "HF"

# Sample types to remove from datatable
params$type.to.remove <- c("Met", "CA", "IQ", "sol", "BL")

# Normalization method
#c("bestis", "low_cv", "pqn", "loess", "sum", "median", "limma")

params$norm.method <- c("bestis", "low_cv", "pqn", "sum", "median", "limma")

run_module(module = "Normalization",
           params = params)

```

#### 5 Merge and map info
```{r 05_Merge, eval = TRUE}

### datatables

params$path.datatable.pos <- paste0(params$path.result, "04_Normalization_comparison/", "pos_normalised_bestis.xlsx")
params$path.datatable.neg <- paste0(params$path.result, "04_Normalization_comparison/", "neg_normalised_bestis.xlsx")

params$datatable.sep <- ";"
params$feature_col_nr <- 2

run_module(module = "Merge",
           params = params)

```

#### 6 QC report
```{r 06_QC_report, eval = TRUE}

run_module(module = "QC_report",
           params = params)

```

```{r session info, include = FALSE}

# Session info

utils::sessionInfo()

```
