---
title: "Data preprocessing workflow"
author: "CBMR Metabolomics Platform"
date: "`r base::Sys.Date()`"

# knit: ( function(inputFile, encoding) { 
#           rmarkdown::render( inputFile, 
#                              encoding = encoding, 
#                              output_file = paste0( substr(inputFile,1,nchar(inputFile)-4), '_', Sys.Date(),'.html')) 
#           })
          
output:
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
  html_notebook:
    toc: yes
    toc_depth: '3'
    df_print: paged
---

```{r setup overall environment, include = FALSE}

wd <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(wd)
library(metpipe)
library(ggplot2)
library(openxlsx)
library(tidyverse)

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  include = FALSE,
  eval = TRUE
)

```

#### Data preprocessing general input
```{r 01_input_general, include = TRUE, echo = TRUE}

params <-
  params_setup( 
    
    path.mzml = "J:/CBMR/SUN-CBMR-Metabolomics/Projects/AMP_test_project/mzML/TE_LIP_MS1/",
    
    standard.name = TRUE,  # TRUE, FALSE
    
    # Metadata
    path.meta.pos = NULL,
    path.meta.neg = NULL,
    
    meta.match.col = "Sample", # "Sample" for standard.name = TRUE, "Sample.name" for 
    
    # Library match
    rt_tolerance = 0.3,
    mz_tolerance = 0.01,
    
    # Pool samples to use for evaluation
    type.use.to.optimize = "PO",  # For optimizing XCMS parameters
    po.sample.to.use = "PO",      # For evaluate normalization
    
    
    ### Only modify if not standard workflow
    method = NULL,
    path.result = NULL,
    sample.pattern = ".mzML",
    
    # Sample path
    # Put "No_data" if not preprocessing the mode
    path.mzml.pos = NULL,
    path.mzml.neg = NULL,
    
    # Library path
    path.lib = "J:/CBMR/SUN-CBMR-Metabolomics/Workflow/library/library.MS1.rds",
    path.lib.is = "J:/CBMR/SUN-CBMR-Metabolomics/Workflow/library/library.MS1.IS.rds",
    path.msp = "J:/CBMR/SUN-CBMR-Metabolomics/Workflow/library/msdial.library.MS1.rds"

)
```

```{r 02_01_Extract_precursor xcms, eval = FALSE}

params$extract_precursor <- TRUE

### XCMS setup
params$optimize.xcms.parameters <- FALSE  # TRUE, FALSE

# If not optimize parameters, the following parameters are used:
params$para.pos <-
  list( # para.peak.picking
        max_peakwidth = 0.7*60,
        min_peakwidth = 0.1*60,
        ppm = 10,
        snthresh = 10,
        noise = 500,
        prefilter = 3,
        value_of_prefilter = 500, 
        
        # para.peak.group
        bw = 0.2*60,
        minFraction.1 = 0.5,
        minFraction.2 = 0.7,
        binSize = 0.01,
        
        # para.adjust.rt
        span = 0.6,
        minFraction.ref = 0.8,
        extraPeaks = 2
  )

params$para.neg <-
  params$para.pos

render_rmarkdown(
    file = system.file("rmd", "Preprocessing_xcms.Rmd", package="metpipe"),
    #file = "Preprocessing_xcms.Rmd",
    params = params[params$Extract_precursor],
    output = paste0( params$path.result, '02_01_Extract_precursor_xcms')
  )

```

```{r 02_02_Extract_precursor msdial, eval = TRUE}

params$extract_precursor <- TRUE

params$mz_tol_pos <- params$mz_tolerance
params$rt_tol_pos <- params$rt_tolerance
params$mz_tol_neg <- params$mz_tol_pos
params$rt_tol_neg <- params$rt_tol_pos

params$ri_tol <- NULL
params$ri_tol_bigger <- NULL

render_rmarkdown(
    file = system.file("rmd", "Untargeted_preprocessing_msdial.Rmd", package="metpipe"),
    #file = "Untargeted_preprocessing_msdial.Rmd",
    params = params[params$Untargeted_preprocessing],
    output = paste0( params$path.result, '02_02_Extract_precursor_msdial')
  )

```


```{r 03_01_Preprocessing_IS, eval = FALSE}

params$preprocessing.is <- TRUE
params$precursor.include <- FALSE

params$mzmine.mz.tol.pos <- params$mz_tolerance
params$mzmine.rt.tol.pos <- params$rt_tolerance
params$mzmine.min.peaks.in.row.pos <- 1
params$mzmine.min.peaks.in.row.pos.percent <- 0

params$mzmine.mz.tol.neg <- params$mzmine.mz.tol.pos
params$mzmine.rt.tol.neg <- params$mzmine.rt.tol.pos
params$mzmine.min.peaks.in.row.neg <- params$mzmine.min.peaks.in.row.pos
params$mzmine.min.peaks.in.row.neg.percent <- params$mzmine.min.peaks.in.row.pos.percent

render_rmarkdown(
    file = system.file("rmd", "Preprocessing_mzmine.Rmd", package="metpipe"),
    #file = "Preprocessing_mzmine.Rmd",
    params = params[params$Preprocessing_IS],
    output = paste0( params$path.result, '03_01_Preprocessing_IS')
    
  )

```

```{r 03_02_QC_IS, eval = FALSE}

params$reference.type <- "reference" # reference or median
params$figure_height <- 900

params$path.peaktable.IS.pos <- NULL
params$path.peaktable.IS.neg <- NULL

params$sample.info.pos.qc <- NULL
params$sample.info.neg.qc <- NULL

render_rmarkdown(
    file = system.file("rmd", "QC_IS.Rmd", package="metpipe"),
    #file = "QC_IS.Rmd",
    params = params[params$QC_IS],
    output = paste0( params$path.result, '03_02_QC_IS')
    
  )

```

```{r 04_01_Preprocessing mzmine, eval = TRUE}

params$precursor.include <- TRUE
params$preprocessing.is <- FALSE

params$mzmine.mz.tol.pos <- params$mz_tolerance
params$mzmine.rt.tol.pos <- params$rt_tolerance
params$mzmine.min.peaks.in.row.pos <- 1
params$mzmine.min.peaks.in.row.pos.percent <- 0

params$mzmine.mz.tol.neg <- params$mzmine.mz.tol.pos
params$mzmine.rt.tol.neg <- params$mzmine.rt.tol.pos
params$mzmine.min.peaks.in.row.neg <- params$mzmine.min.peaks.in.row.pos
params$mzmine.min.peaks.in.row.neg.percent <- params$mzmine.min.peaks.in.row.pos.percent

render_rmarkdown(
    file = system.file("rmd", "Preprocessing_mzmine.Rmd", package="metpipe"),
    #file = "Preprocessing_mzmine.Rmd",
    params = params[params$Preprocessing],
    output = paste0( params$path.result, '04_01_Preprocessing_mzmine')
  )


```

```{r 04_02_Untargeted_preprocessing xcms, eval = FALSE}

params$extract_precursor <- FALSE

### XCMS setup
params$optimize.xcms.parameters <- FALSE  # TRUE, FALSE

# If not optimize parameters, the following parameters are used:
params$para.pos <-
  list( # para.peak.picking
        max_peakwidth = 0.7*60,
        min_peakwidth = 0.1*60,
        ppm = 10,
        snthresh = 10,
        noise = 500,
        prefilter = 3,
        value_of_prefilter = 500, 
        
        # para.peak.group
        bw = 0.2*60,
        minFraction.1 = 0.5,
        minFraction.2 = 0.7,
        binSize = 0.01,
        
        # para.adjust.rt
        span = 0.6,
        minFraction.ref = 0.8,
        extraPeaks = 2
  )

params$para.neg <-
  params$para.pos

render_rmarkdown(
    file = system.file("rmd", "Preprocessing_xcms.Rmd", package="metpipe"),
    #file = "Preprocessing_xcms.Rmd",
    params = params[params$Extract_precursor],
    output = paste0( params$path.result, '04_02_Extract_precursor_xcms')
  )

```


```{r 04_03_Untargeted_preprocessing msdial, eval = FALSE}

params$extract_precursor <- FALSE

params$mz_tol_pos <- params$mz_tolerance
params$rt_tol_pos <- params$rt_tolerance
params$mz_tol_neg <- params$mz_tol_pos
params$rt_tol_neg <- params$rt_tol_pos

params$ri_tol <- NULL
params$ri_tol_bigger <- NULL
  
render_rmarkdown(
    file = system.file("rmd", "Untargeted_preprocessing_msdial.Rmd", package="metpipe"),
    #file = "Untargeted_preprocessing_msdial.Rmd",
    params = params[params$Untargeted_preprocessing],
    output = paste0( params$path.result, '04_03_Untargeted_preprocessing')
  )


```

```{r 05_Clean_peaktable, eval = TRUE}

### Peaktable

params$path.peaktable.pos <- NULL
params$path.peaktable.neg <- NULL

params$peaktable.sep <- ";"
params$peaktable.sample.pattern <- ".mzML Peak area"

params$mz_col_nr <- 2
params$rt_col_nr <- 3
params$identity_col_nr <- 4
params$others <- c()

### Peak cleaning setup

# Feature filtering
params$bl.thres <- c( 3, "BL", "<", "PO")            # 3, mean in PO should be > 3 times BL
params$rsd.po.thres <- c( "PO", "<", 40)        # 50, RSD in PO should be < 50%
params$mean.po.thres <- c( "PO", ">", 1000) 
params$rt.range <- c(0.8, 30)         # c(0, 30), only keep peaks in 0 - 30 min
params$mean.thres <- c()

# Filter based on missings
params$filter_by_missing_feature_pct <- 50

# Missing imputation
params$missing.impute.method <- "LoD"  # "LoD", "HF", "median", "min", "mean"

render_rmarkdown(
    file = system.file("rmd", "Clean_peaktable.Rmd", package="metpipe"),
    #file = "Clean_peaktable.Rmd",
    params = params[params$Clean_peaktable],
    output = paste0( params$path.result, '05_Clean_peaktable')
  )

```

```{r 06_Normalization_comparison, eval = TRUE}

### Peaktable

params$path.peaktable.pos <- NULL
params$path.peaktable.neg <- NULL

params$peaktable.sep <- ";"
params$peaktable.sample.pattern <- ".mzML Peak area"

params$mz_col_nr <- 1
params$rt_col_nr <- 2
params$identity_col_nr <- 3
params$sample_col_nr <- 4
params$others <- c()

### Processing parameters
# Filter based on missings

params$missing.sample.thres <- 30
params$missing.feature.thres <- 30

# Misssing imputation
# "LoD", "HF", "median", "min", "mean"

params$missing.impute.method.sample <- "LoD"  
params$missing.impute.method.is <- "LoD"

# Outlier removal

params$outliers.sample <- NULL
params$outliers.feature <- NULL
params$outliers.is <- NULL

# Sample types to remove from datatable
params$type.to.remove <- c("Met", "CA", "IQ", "sol", "BL")

# Normalization method
#c("bestis", "low_cv", "pqn", "nomis", "qspline", "loess", "sum", "median", "combat", "limma")

params$norm.method <- c("bestis", "low_cv", "sum", "median")

render_rmarkdown(
    file = system.file("rmd", "Normalization_comparison.Rmd", package="metpipe"),
    #file = "Normalization_comparison.Rmd",
    params = params[params$Normalization_comparison],
    output = paste0( params$path.result, '06_Normalization_comparison')
  )

```

```{r 07_Merge_and_map_names, eval = FALSE}

### datatables

params$path.datatable.pos <- paste0(params$path.result, "06_Normalization_comparison/", "pos_normalised_bestis.xlsx")
params$path.datatable.neg <- paste0(params$path.result, "06_Normalization_comparison/", "neg_normalised_bestis.xlsx")

params$datatable.sep <- ";"
params$feature_col_nr <- 2

render_rmarkdown(
    #file = system.file("rmd", "Merge_and_map_names.Rmd", package="metpipe"),
    file = "Merge_and_map_names.Rmd",
    params = params[params$Merge_and_map_names],
    output = paste0( params$path.result, '07_Merge_and_map_names')
  )

```

```{r session info, include = FALSE}

# Session info

utils::sessionInfo()

```
