---
title: "Preprocessing XCMS"
author: "`r params$author`"
date: "`r base::Sys.Date()`"

knit: ( function(inputFile, encoding) { 
          rmarkdown::render( inputFile, 
                             encoding = encoding, 
                             output_file = paste0( substr(inputFile,1,nchar(inputFile)-4), '_', Sys.Date(),'.html')) 
          })
          
output:
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: false
    toc_depth: '4'
    df_print: paged
---

<style type="text/css">
body{
  font-size: 12px;
  }
td {
  font-size: 14px;
}
h1.title {
  font-size: 22px;
}
h4.author {
  font-size: 16px;
}
h4.date {
  font-size: 16px;
}

h1 {
  font-size: 18px;
}
h2 {
  font-size: 16px;
}
h3 {
  font-size: 14px;
}
h4 {
  font-size: 12px;
}
h5 {
  font-size: 12px;
}
code.r{
  font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
  font-size: 14px;
}
</style>

```{r setup environment, include = FALSE}

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  include = TRUE
)

```

# Preprocessing using XCMS
```{r set environment variables}

if (params$extract_precursor){

  path.output <-
    paste0(params$path.result, "02_Extract_precursor/")
  
  path.mzml.pos <- paste0(params$path.mzml.pos, "/subset/")
  path.mzml.neg <- paste0(params$path.mzml.neg, "/subset/")
  output.file.pos <- paste0(path.output, "precursor_annotation_pos.csv")
  output.file.neg <- paste0(path.output, "precursor_annotation_neg.csv")
    
} else {
  
  path.output <-
    paste0(params$path.result, "02_Preprocessing/")
  
  path.mzml.pos <- params$path.mzml.pos
  path.mzml.neg <- params$path.mzml.neg
  output.file.pos <- paste0(path.output, "peaktable_pos.csv")
  output.file.neg <- paste0(path.output, "peaktable_neg.csv")
}

if (!dir.exists(path.output)) dir.create(path.output)

# print( "Raw data was imported from the following folder:", quote = FALSE)
# print( paste0("POS: ", params$path.mzml.pos), quote = FALSE)
# print( paste0("NEG: ", params$path.mzml.neg), quote = FALSE)
# print( paste0("Other metadata: "), quote = FALSE)
# print( paste0("POS: ", params$path.meta.pos), quote = FALSE)
# print( paste0("NEG: ", params$path.meta.neg), quote = FALSE)
# 
# print( "Result is stored in the following folder:", quote = FALSE)
# print( path.output, quote = FALSE)

```

## Positive mode parameters
```{r sample info pos, eval = params$run.pos}
### 1 Data import
if (params$extract_precursor){
  
  #file.name.pos <- list.files(path.mzml.pos, pattern = "mzML")
  sample.info.pos <-
    extract_sample_info( path = path.mzml.pos,
                         sample.pattern = params$sample.pattern,
                         standard.name = FALSE) %>%
    filter( !grepl("ms2p", tolower(Sample.name)))
    #filter(File.name %in% file.name.pos)
  
} else {
  
  sample.info.pos <- 
      params$sample.info.pos
  
}

### Save parameters
saveRDS( params$para.pos, 
         file = paste0(path.output, "XCMS_parameters_", "pos", ".rds"))

print( "Raw data was imported from the following folder:", quote = FALSE)
print( params$path.mzml.pos, quote = FALSE)
print( paste0("POS peaktable was saved as: ", output.file.pos), quote = FALSE)
print( paste0("Library file: ", path.output, "library_MS1_", params$method, "_pos.csv"), quote = FALSE)

print( "XCMS parameters used in positive mode:", quote = FALSE)
print( params$para.pos, quote = FALSE)

```

## Negative mode parameters
```{r sample info neg, eval = params$run.neg}

if (params$extract_precursor){

  #file.name.neg <- list.files(path.mzml.neg, pattern = "mzML")
  sample.info.neg <-
    extract_sample_info( path = path.mzml.neg,
                         sample.pattern = params$sample.pattern,
                         standard.name = FALSE) %>%
    filter( !grepl("ms2n", tolower(Sample.name)))
    #filter(File.name %in% file.name.neg)
  
} else {
  
  sample.info.neg <- 
      params$sample.info.neg
  
}

### Save parameters    
saveRDS( params$para.neg, 
         file = paste0(path.output, "XCMS_parameters_", "neg", ".rds"))

print( "Raw data was imported from the following folder:", quote = FALSE)
print( params$path.mzml.neg, quote = FALSE)
print( paste0("NEG peaktable was saved as: ", output.file.neg), quote = FALSE)
print( paste0("Library file: ", path.output, "library_MS1_", params$method, "_neg.csv"), quote = FALSE)

print( "XCMS parameters used in negative mode:", quote = FALSE)
print( params$para.pos, quote = FALSE)

```


```{r preprocessing pos, eval = params$run.pos}

### Preprocessing

peaks.pos <-
    process_peak_group( para = params$para.pos,
                        sample.info = sample.info.pos,
                        mode = "pos",
                        path.result = path.output,
                        BPPARAM = params$BPPARAM_set)

### Precursor selection

precursor.pos <-
  select_precursor( XCMSnExp = peaks.pos,
                    method = "camera",
                    mode = "pos",
                    path.result = path.output,
                      BPPARAM = params$BPPARAM_set )

```

```{r match library pos, eval = params$run.pos}

#print( paste0( "POS: ", nrow(precursor.pos), " precursors has been selected in raw data"), quote = FALSE)

lib.to.use <-
  bind_rows(params$lib[[params$method]]$pos, 
            params$lib.is[[params$method]]$pos %>%
              select( Library.mz, Library.rt, Library.name))

library.file <- paste0(path.output, "library_MS1_", params$method, "_neg.csv")

write.table( lib.to.use, 
         sep = ";",
         row.names = FALSE,
         file = library.file )

precursor.pos.annotated <- 
  match_library( feature_info = precursor.pos,
                 rt_tolerance = params$rt_tolerance,
                 mz_tolerance = params$mz_tolerance,
                 library_file = lib.to.use,
                 mode = "pos",
                 output.file = output.file.pos )

```

```{r deisotope pos, eval = params$run.pos}

precursor.pos.annotated.deiso <- 
  precursor.pos.annotated %>% 
  filter( !grepl("Unknown_", Library.name, fixed = TRUE) |
          (grepl("Unknown_", Library.name, fixed = TRUE) & ((is.na(isotopes) | isotopes == "" ) | grepl("[M]", isotopes, fixed = TRUE))) 
          )

saveRDS(precursor.pos.annotated.deiso, file = paste0(path.output, "/precursor_annotation_pos.rds"))   
#print( paste0("POS preprocessed data were saved as: ", output.file.pos), quote = FALSE)

```


```{r preprocessing neg, eval = params$run.neg}

### Preprocessing

peaks.neg <-
    process_peak_group( para = params$para.neg,
                        sample.info = sample.info.neg,
                        mode = "neg",
                        path.result = path.output,
                        BPPARAM = params$BPPARAM_set )

### Precursor selection

precursor.neg <-
  select_precursor( XCMSnExp = peaks.neg,
                    method = "camera",
                    mode = "neg",
                    path.result = path.output,
                    BPPARAM = params$BPPARAM_set )
  
```


```{r match library neg, eval = params$run.neg}
  
#print( paste0( "NEG: ", nrow(precursor.neg), " precursors has been selected in raw data"), quote = FALSE)

lib.to.use <-
  bind_rows(params$lib[[params$method]]$pos, 
            params$lib.is[[params$method]]$pos %>%
              select( Library.mz, Library.rt, Library.name))

library.file <- paste0(path.output, "library_MS1_", params$method, "_neg.csv")

write.table( lib.to.use, 
         sep = ";",
         row.names = FALSE,
         file = library.file )

precursor.neg.annotated <- 
  match_library( feature_info = precursor.neg,
                 rt_tolerance = params$rt_tolerance,
                 mz_tolerance = params$mz_tolerance,
                 library_file = lib.to.use,
                 mode = "neg",
                 output.file = output.file.neg )

```

```{r deisotope neg, eval = params$run.neg}

precursor.neg.annotated.deiso <- 
  precursor.neg.annotated %>% 
  filter( !grepl("Unknown_", Library.name, fixed = TRUE) |
          (grepl("Unknown_", Library.name, fixed = TRUE) & ((is.na(isotopes) | isotopes == "" ) | grepl("[M]", isotopes, fixed = TRUE))) 
          )

saveRDS(precursor.neg.annotated.deiso, file = paste0(path.output, "/precursor_annotation_neg.rds"))
#print( paste0("NEG preprocessed data were saved as: ", output.file.neg), quote = FALSE)

```

```{r SessionInfo, include = FALSE}

# Session info

utils::sessionInfo()

```
