---
title: "Untargeted preprocessing"
author: "CBMR Metabolomics Platform"
date: "`r base::Sys.Date()`"

knit: ( function(inputFile, encoding) { 
          rmarkdown::render( inputFile, 
                             encoding = encoding, 
                             output_file = paste0( substr(inputFile,1,nchar(inputFile)-4), '_', Sys.Date(),'.html')) 
          })
          
output:
  html_document:
    toc: yes
    toc_depth: '4'
    df_print: paged
  html_notebook:
    toc: yes
    toc_depth: '4'
    df_print: paged
---

```{r setup environment, include = FALSE}

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  include = TRUE
)

```

```{r set environment variables}

if (params$extract_precursor){

  path.output <-
    paste0(params$path.result, "02_Extract_precursor/")
  
  path.mzml.pos <- paste0(params$path.mzml.pos, "/subset/")
  path.mzml.neg <- paste0(params$path.mzml.neg, "/subset/")
  output.file.pos <- paste0(path.output, "precursor_annotation_pos.csv")
  output.file.neg <- paste0(path.output, "precursor_annotation_neg.csv")
  
  file.name.pos <- list.files(path.mzml.pos, pattern = "mzML")
  sample.info.pos <-
    extract_sample_info( path = params$path.mzml.pos,
                         sample.pattern = params$sample.pattern,
                         standard.name = FALSE) %>%
    filter(File.name %in% file.name.pos)
  
  file.name.neg <- list.files(path.mzml.neg, pattern = "mzML")
  sample.info.neg <-
    extract_sample_info( path = params$path.mzml.neg,
                         sample.pattern = params$sample.pattern,
                         standard.name = FALSE) %>%
    filter(File.name %in% file.name.neg)
    
} else {
  
  path.output <-
    paste0(params$path.result, "04_Preprocessing/")
  
  path.mzml.pos <- params$path.mzml.pos
  path.mzml.neg <- params$path.mzml.neg
  output.file.pos <- paste0(path.output, "peaktable_targeted_pos.csv")
  output.file.neg <- paste0(path.output, "peaktable_targeted_neg.csv")
  
  sample.info.pos <- params$sample.info.pos
  sample.info.neg <- params$sample.info.neg

}

path.output.pos <-
  paste0(path.output, "pos/")
 
path.output.neg <-
  paste0(path.output, "neg/")

if (!dir.exists(path.output)) dir.create(path.output)
if (!dir.exists(path.output.pos)) dir.create(path.output.pos)
if (!dir.exists(path.output.neg)) dir.create(path.output.neg)

mz_tol_pos = params$mz_tol_pos
mz_tol_bigger_pos = params$mz_tol_pos+0.003
rt_tol_pos = params$rt_tol_pos
rt_tol_bigger_pos = params$rt_tol_pos+0.1

mz_tol_neg = params$mz_tol_neg
mz_tol_bigger_neg = params$mz_tol_neg+0.003
rt_tol_neg = params$rt_tol_neg
rt_tol_bigger_neg = params$rt_tol_neg+0.1


if (params$target == "GC"){
  process_type <- "gcms"
} else {
  process_type <- "lcmsdda" 
}

```

### Preprocessing using MSDIAL
#### POS
```{r generate library pos, eval = params$run.pos}

lib.to.use <-
    bind_rows(params$lib[[params$method]]$pos, 
              params$lib.is[[params$method]]$pos %>%
                select( Library.mz, Library.rt, Library.name, Ion)) %>%    
    select("Library.name", "Library.mz", "Library.rt", "Library.name", "Ion", "Inchikey", "Molecular.formula", "Smiles") %>%
    dplyr::rename( name = Library.name,
                   mz = Library.mz,
                   rt = Library.rt,
                   adduct = Ion) %>%
    mutate(name = paste0(name, ";"))

library.file <- paste0(path.output, "MSDIAL_library_MS1_", params$method, "_pos.txt")

write.table( lib.to.use, 
             file = library.file, 
             sep = "\t", 
             row.names = FALSE, 
             quote = FALSE)

if ( file.exists( "/home/projects/ku_00007/" )){
  msp.file <- params$msp$linux[[params$target]]$pos
  path_ri <- params$msp$linux$GC$ri
} else {
  msp.file <- params$msp[[params$target]]$pos
  path_ri <- params$msp$GC$ri
}

print( paste0("POS peaktable was saved as: ", output.file.pos), quote = FALSE)
print( paste0("Library file: ", library.file), quote = FALSE)
print( "MSDIAL parameters used in positive mode:")

print( paste0("mz_tol_pos = ", mz_tol_pos), quote = FALSE)
print( paste0("mz_tol_bigger_pos = ", mz_tol_bigger_pos), quote = FALSE)
print( paste0("rt_tol_pos = ", rt_tol_pos), quote = FALSE)
print( paste0("rt_tol_bigger_pos = ", rt_tol_bigger_pos), quote = FALSE)

```

```{r generate parameters pos, echo = TRUE, eval = params$run.pos}

ref.samples <-
  params$sample.info.pos %>%
  filter(Sample.type == params$po.sample.to.use) %>%
  pull(File.path)

params$align_ref <- ref.samples[1]

if (!file.exists(paste0(path.output, "/MSDIAL_parameters_pos.txt"))){
  prepare_msdial_txt(
      target = params$target, # Metabolomics, Lipidomics
      mode = 'Positive',
      path_lib = library.file,
      path_msp = msp.file,
      path_ri = path_ri,
      mz_tol = mz_tol_pos,
      mz_tol_bigger = mz_tol_bigger_pos,
      rt_tol = rt_tol_pos,
      rt_tol_bigger = rt_tol_bigger_pos,
      ri_tol = params$ri_tol,
      ri_tol_bigger = params$ri_tol_bigger,   
      align_ref = params$align_ref,
      output_file = paste0(path.output, "/MSDIAL_parameters_pos.txt")
    )
}
```

```{r data preprocessing pos, include = FALSE, eval = params$run.pos}

temp.file <- list.files( path = path.output.pos,
              pattern = "^AlignResult.*\\.msdial$",
              full.names = TRUE)

if (length(temp.file) == 0) temp.file <- ""

if ( file.exists( "/home/projects/ku_00007/" ) & !file.exists(temp.file) ) {
  setwd('/home/projects/ku_00007/apps/MSDIAL/MSDIAL_ver.4.9')
  system( paste0( 'bash cd /home/projects/ku_00007/apps/MSDIAL/MSDIAL_ver.4.9; ./MsdialConsoleApp ',
                                        process_type,
                                ' -i ', path.mzml.pos,    
                                ' -o ', path.output.pos,
                                ' -m ', path.output, 'MSDIAL_parameters_pos.txt -p') )
  
} else if (!file.exists(temp.file)) {
  
  system("cmd.exe", input = paste0( params$path.msdial,
                                    " ",    process_type,
                                    " -i ", path.mzml.pos,    
                                    " -o ", path.output.pos,
                                    " -m ", path.output, "MSDIAL_parameters_pos.txt -p"))
  
}

```

```{r grouping pos, include = FALSE, eval = params$run.pos}

pdata <-
  read.delim(list.files( path = path.output.pos,
              pattern = "^AlignResult.*\\.msdial$",
              full.names = TRUE), 
             skip = 4, 
             check.names = FALSE)

output_data <-
  pdata %>%
  select("Alignment ID", "Average Mz", "Average Rt(min)",
         "Metabolite name", "Adduct type", "Formula", 
         "Annotation tag (VS1.0)", "MS/MS assigned", "MS/MS matched", 
         "Total score", "RT similarity", "Dot product", "Fragment presence %", "S/N average",
         sample.info.pos$Sample.name) %>%
  dplyr::rename( rt = "Average Rt(min)",
                 mz = "Average Mz",
                 Library.name = "Metabolite name") %>%
  filter(`S/N average` > 10) %>%
  group_by(Library.name) %>%
  mutate( Library.name = trimws(Library.name),
          Library.name = ifelse( Library.name == "Unknown", 
                                    paste0("Unknown_pos_", row_number()),
                                    ifelse(substr(Library.name, nchar(Library.name), nchar(Library.name)) == ";",
                                          substr(Library.name, 1, nchar(Library.name) -1),
                                          Library.name)),
          Library.name = case_when(`Annotation tag (VS1.0)` == "annotated by user-defined text library"  ~ Library.name,
                                   `Annotation tag (VS1.0)` %in% c("410", "420", "430")                  ~ paste0( "w MS2:", Library.name),
                                   TRUE                                ~ Library.name)) %>%
  ungroup() %>%
  filter(!grepl("[(d)]", Library.name, fixed = TRUE)) %>%
  mutate( `Adduct type` = trimws(`Adduct type`))

write.table(output_data,
          file = output.file.pos,
          sep = ";",
          row.names = FALSE)

if (params$extract_precursor){
  
  final <-
    output_data %>%
    mutate( Library.rt = ifelse( substr(Library.name, 1, 9) %in% c("in_house:"), 99, NA))
    
  saveRDS( final,
           file = paste0(path.output, "precursor_annotation_pos.rds") )
  
}

```

#### NEG
```{r generate library neg, eval = params$run.neg}

lib.to.use <-
    bind_rows(params$lib[[params$method]]$neg, 
              params$lib.is[[params$method]]$neg %>%
                select( Library.mz, Library.rt, Library.name, Ion)) %>%    
    select("Library.name", "Library.mz", "Library.rt", "Ion", "Inchikey", "Molecular.formula", "Smiles") %>%
    dplyr::rename( name = Library.name,
                   mz = Library.mz,
                   rt = Library.rt,
                   adduct = Ion) %>%
    mutate(name = paste0(name, ";"))

library.file <- paste0(path.output, "MSDIAL_library_MS1_", params$method, "_neg.txt")

write.table( lib.to.use, 
             file = library.file, 
             sep = "\t", 
             row.names = FALSE, 
             quote = FALSE)

if ( file.exists( "/home/projects/ku_00007/" )){
  msp.file <- params$msp$linux[[params$target]]$neg
} else {
  msp.file <- params$msp[[params$target]]$neg  
}

print( paste0("NEG peaktable was saved as .msdial file in: ", path.output), quote = FALSE)
print( paste0("Library file: ", library.file), quote = FALSE)
print( "MSDIAL parameters used in negative mode:")

print( paste0("mz_tol_neg = ", mz_tol_neg), quote = FALSE)
print( paste0("mz_tol_bigger_neg = ", mz_tol_bigger_neg), quote = FALSE)
print( paste0("rt_tol_neg = ", rt_tol_neg), quote = FALSE)
print( paste0("rt_tol_bigger_neg = ", rt_tol_bigger_neg), quote = FALSE)

```

```{r generate parameters neg, echo = TRUE, eval = params$run.neg}

ref.samples <-
  params$sample.info.neg %>%
  filter(Sample.type == params$po.sample.to.use) %>%
  pull(File.path)

params$align_ref <- ref.samples[1]

if (!file.exists(paste0(path.output, "/MSDIAL_parameters_neg.txt"))){
  prepare_msdial_txt(
      target = params$target, # Metabolomics, Lipidomics
      mode = 'Negative',
      path_lib = library.file,
      path_msp = msp.file,
      mz_tol = mz_tol_neg,
      mz_tol_bigger = mz_tol_bigger_neg,
      rt_tol = rt_tol_neg,
      rt_tol_bigger = rt_tol_bigger_neg,
      align_ref = params$align_ref,
      output_file = paste0(path.output, "/MSDIAL_parameters_neg.txt")
    )
}
```

```{r data preprocessing neg, include = FALSE, eval = params$run.neg}

temp.file <- list.files( path = path.output.neg,
              pattern = "^AlignResult.*\\.msdial$",
              full.names = TRUE)

if (length(temp.file) == 0) temp.file <- ""

if ( file.exists( "/home/projects/ku_00007/" ) & !file.exists(temp.file) ) {
  setwd('/home/projects/ku_00007/apps/MSDIAL/MSDIAL_ver.4.9')
  system( paste0( 'bash cd /home/projects/ku_00007/apps/MSDIAL/MSDIAL_ver.4.9; ./MsdialConsoleApp ',
                                        process_type,
                                ' -i ', path.mzml.neg,    
                                ' -o ', path.output.neg,
                                ' -m ', path.output, 'MSDIAL_parameters_neg.txt -p') )
  
} else if (!file.exists(temp.file)) {
  
  system("cmd.exe", input = paste0( params$path.msdial,
                                    " ",    process_type,
                                    " -i ", path.mzml.neg,    
                                    " -o ", path.output.neg,
                                    " -m ", path.output, "MSDIAL_parameters_neg.txt -p"))
  
}

```

```{r grouping neg, include = FALSE, eval = params$run.neg}

pdata <-
  read.delim(list.files( path = path.output.neg,
              pattern = "^AlignResult.*\\.msdial$",
              full.names = TRUE), 
             skip = 4, 
             check.names = FALSE)

output_data <-
  pdata %>%
  select("Alignment ID", "Average Mz", "Average Rt(min)",
         "Metabolite name", "Adduct type", "Formula", 
         "Annotation tag (VS1.0)", "MS/MS assigned", "MS/MS matched", 
         "Total score", "RT similarity", "Dot product", "Fragment presence %", "S/N average",
         sample.info.neg$Sample.name) %>%
  dplyr::rename( rt = "Average Rt(min)",
                 mz = "Average Mz",
                 Library.name = "Metabolite name") %>%
  filter(`S/N average` > 10) %>%
  group_by(Library.name) %>%
  mutate( Library.name = trimws(Library.name),
          Library.name = ifelse( Library.name == "Unknown", 
                                    paste0("Unknown_neg_", row_number()),
                                    ifelse(substr(Library.name, nchar(Library.name), nchar(Library.name)) == ";",
                                          substr(Library.name, 1, nchar(Library.name) -1),
                                          Library.name)),
          Library.name = case_when(`Annotation tag (VS1.0)` == "annotated by user-defined text library"  ~ Library.name,
                                   `Annotation tag (VS1.0)` %in% c("410", "420", "430")                  ~ paste0( "w MS2:", Library.name),
                                   TRUE                                ~ Library.name)) %>%
  ungroup() %>%
  filter(!grepl("[(d)]", Library.name, fixed = TRUE)) %>%
  mutate( `Adduct type` = trimws(`Adduct type`))

write.table(output_data,
          file = output.file.neg,
          sep = ";",
          row.names = FALSE)


if (params$extract_precursor){
  
  final <-
    output_data %>%
    mutate( Library.rt = ifelse( substr(Library.name, 1, 9) %in% c("in_house"), 99, NA))
    
  saveRDS( final,
           file = paste0(path.output, "precursor_annotation_neg.rds") )
  
}

```

```{r SessionInfo, include = FALSE}

# Session info

utils::sessionInfo()

```
