---
title: "Preprocessing with mzmine"
author: "CBMR Metabolomics Platform"
date: "`r base::Sys.Date()`"
          
output:
  html_document:
    theme: flatly
    toc: yes
    toc_float:
      collapsed: false
    toc_depth: '3'
    number_sections: true
    df_print: paged

params:
  config: ""
---
<style type="text/css">
body{
  font-size: 12px;
  }
td {
  font-size: 14px;
}
h1.title {
  font-size: 22px;
}
h4.author {
  font-size: 16px;
}
h4.date {
  font-size: 16px;
}

h1 {
  font-size: 18px;
}
h2 {
  font-size: 16px;
}
h3 {
  font-size: 14px;
}
h4 {
  font-size: 12px;
}
h5 {
  font-size: 12px;
}
code.r{
  font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
  font-size: 14px;
}
</style>

```{r setup environment, include = FALSE, warning = FALSE}

library(yaml)
library(xml2)

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  include = TRUE
)

```

```{r pipeline input}

config <- read_yaml(params$config)

path_raw = config$path_raw
path_result = config$path_result
path_mzmine = config$path_mzmine
path_temp = config$path_temp

method_name = config$method_name
run.pos = config$run.pos
raw_files_pos = config$raw_files_pos
run.neg = config$run.neg
raw_files_neg = config$raw_files_neg
mzmine_params = config$mzmine_params 
# path_lib_pos = config$path_lib_pos
# path_lib_neg = config$path_lib_neg
path_lib_istd_pos = config$path_lib_istd_pos
path_lib_istd_neg = config$path_lib_istd_neg
sepectral_lib = config$sepectral_lib
path_spectral_lib = config$path_spectral_lib
mzmine_user = config$mzmine_user
mzmine_memory <- config$mzmine_memory
mzmine_threads <- config$mzmine_threads
# output
mzmine_peaktable_pos <- config$mzmine_peaktable_pos
mzmine_peaktable_neg <- config$mzmine_peaktable_neg
```

# Method configuration
```{r}

cat("Method name: ", method_name, "\n")
cat("In house libraries used for preprocessing: \n")
if (!is.na(path_lib_istd_pos)) cat(path_lib_istd_pos, "\n")
if (!is.na(path_lib_istd_neg)) cat(path_lib_istd_neg, "\n")
# if (!is.na(path_lib_pos)) cat(path_lib_pos, "\n")
# if (!is.na(path_lib_neg)) cat(path_lib_neg, "\n")
cat("Spectral libraries used for preprocessing: \n")
cat(path_spectral_lib, "\n")
cat("mzmine parameter file used for preprocessing: \n")
cat(mzmine_params, "\n")
```

# Raw data files
```{r}

cat("Raw data for preprocessing are stored in: \n")
cat(path_raw, "\n")

```

# Preprocessing
```{r}

if (!dir.exists(path_result)) dir.create(path_result)

```

## Positive
```{r, eval = run.pos}

path_output <- paste0(path_result, "/pos")
dir.create(path_output)
cat("Processed data in positive mode is stored in: \n")
cat(path_output, "\n")

raw_files <- raw_files_pos
# path_lib <- list(path_lib_istd_pos, path_lib_pos)
# path_lib <- path_lib[!is.na(path_lib)]
path_lib <- path_lib_istd_pos
parameters <- read_xml(mzmine_params)
param_file <- paste0(path_output, "/mzmine_parameters_pos.mzbatch")

if (!file.exists(param_file)){
  file_names_node <- xml_find_first(parameters, "//parameter[@name='File names']")
  new_files <- raw_files
  
  for (f in new_files) {
    xml_add_child(file_names_node, "file", f)
  }
  
  file_names_node <- xml_find_first(parameters, "//parameter[@name='Database file']")
  
  #for (f in path_lib) {
    xml_add_child(file_names_node, "current_file", path_lib)
  #}  
  
  file_names_node <- xml_find_first(parameters, "//parameter[@name='Spectral library files']")
  
  for (f in path_spectral_lib) {
    xml_add_child(file_names_node, "file", f)
  }
  
  write_xml(parameters, param_file)
}

if (!file.exists(mzmine_peaktable_pos)){
  if (grepl(".exe", path_mzmine)){
    system("cmd.exe", input = paste0(path_mzmine,
           ' -user ', mzmine_user,
           ' -batch ', param_file,
           ' -output ', path_output,
           ' ', mzmine_memory,
           ' ', mzmine_threads,
           ' -temp ', path_temp))
  } else {
    system(paste0(path_mzmine,
           ' -user ', mzmine_user, 
           ' -batch ', param_file,
           ' -output ', path_output,
           ' ', mzmine_memory,
           ' ', mzmine_threads,
           ' -temp ', path_temp))  
  }
} else {
  cat('raw neg is already preprocessed, skipped this step.')
}

```

## Negative
```{r, eval = run.neg}

path_output <- paste0(path_result, "/neg")
dir.create(path_output)
cat("Processed data in negative mode is stored in: \n")
cat(path_output, "\n")

raw_files <- raw_files_neg
# path_lib <- list(path_lib_istd_neg, path_lib_neg)
# path_lib <- path_lib[!is.na(path_lib)]
path_lib <- path_lib_istd_neg
parameters <- read_xml(mzmine_params)
param_file <- paste0(path_output, "/mzmine_parameters_neg.mzbatch")

if (!file.exists(param_file)){
  file_names_node <- xml_find_first(parameters, "//parameter[@name='File names']")
  new_files <- raw_files
  
  for (f in new_files) {
    xml_add_child(file_names_node, "file", f)
  }
  
  file_names_node <- xml_find_first(parameters, "//parameter[@name='Database file']")
  
  #for (f in path_lib) {
    xml_add_child(file_names_node, "current_file", path_lib)
  #}
  
  file_names_node <- xml_find_first(parameters, "//parameter[@name='Spectral library files']")
  
  for (f in path_spectral_lib) {
    xml_add_child(file_names_node, "file", f)
  }
    
  write_xml(parameters, param_file)
}

if (!file.exists(mzmine_peaktable_neg)){
  if (grepl(".exe", path_mzmine)){
    system("cmd.exe", input = paste0(path_mzmine,
           ' -user ', mzmine_user,
           ' -batch ', param_file,
           ' -output ', path_output,
           ' ', mzmine_memory,
           ' ', mzmine_threads,
           ' -temp ', path_temp))
  } else {
    system(paste0(path_mzmine,
           ' -user ', mzmine_user, 
           ' -batch ', param_file,
           ' -output ', path_output,
           ' ', mzmine_memory,
           ' ', mzmine_threads,
           ' -temp ', path_temp))  
  }
} else {
  cat('raw neg is already preprocessed, skipped this step.')
}

```

```{r SessionInfo, include = FALSE}

# Session info

utils::sessionInfo()

```
