---
title: "QC internal standards"
author: "CBMR Metabolomics Platform"
date: "`r base::Sys.Date()`"
          
format:
  html:
    toc: true
    toc-depth: 3
    toc-expand: 2
    toc-location: left
    theme: flatly
    polyfill: false
    page-layout: full
    number-sections: true
    number-depth: 2
self-contained: true

params:
  config: ""
---

```{r setup environment, include = FALSE, warning = FALSE}


library(plotly)
library(knitr)
library(kableExtra)
library(tidyr)
library(dplyr)
library(stringr)
library(htmltools)
library(ggsci)
library(yaml)

helper_candidates <- c(
  file.path(getwd(), "helpers_workflow.R"),
  file.path(getwd(), "inst", "scripts", "helpers_workflow.R"),
  system.file("scripts", "helpers_workflow.R", package = "metpipe")
)
helper_candidates <- helper_candidates[file.exists(helper_candidates)]
if (length(helper_candidates) == 0) {
  stop("Cannot locate shared helper script helpers_workflow.R")
}
source(helper_candidates[[1]], local = TRUE)

metpipe_runtime <- wf_load_metpipe_runtime()

is_blank <- wf_is_blank
as_flag <- wf_as_flag
cfg_required <- wf_cfg_required
as_meta_df <- wf_as_meta_df

knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE,
  echo = FALSE,
  include = TRUE
)

```

```{r pipeline input}

config <- wf_read_yaml_config(params$config, label = "params$config")

method_name <- cfg_required(config, "method_name")
path_lib_istd_pos <- config$path_lib_istd_pos
path_lib_istd_neg <- config$path_lib_istd_neg
run.pos <- as_flag(config$run.pos)
run.neg <- as_flag(config$run.neg)
meta_pos <- as_meta_df(config$meta_pos)
meta_neg <- as_meta_df(config$meta_neg)
figure_height = config$figure_height
figure_width = config$figure_width
path_peaktable_istd_pos <- config$path_peaktable_istd_pos
path_peaktable_istd_neg <- config$path_peaktable_istd_neg

# output
rds_qc_is_pos <- config$rds_qc_is_pos
rds_qc_is_neg <- config$rds_qc_is_neg

if (!run.pos && !run.neg) {
  stop("Both run.pos and run.neg are FALSE. Nothing to evaluate.")
}

if (run.pos) {
  path_lib_istd_pos <- cfg_required(config, "path_lib_istd_pos")
  path_peaktable_istd_pos <- cfg_required(config, "path_peaktable_istd_pos")
  rds_qc_is_pos <- cfg_required(config, "rds_qc_is_pos")
  if (is.null(meta_pos)) stop("run.pos=TRUE but meta_pos is missing")
  if (!file.exists(path_lib_istd_pos)) stop("Positive ISTD library file not found: ", path_lib_istd_pos)
  if (!file.exists(path_peaktable_istd_pos)) stop("Positive ISTD peaktable file not found: ", path_peaktable_istd_pos)
}

if (run.neg) {
  path_lib_istd_neg <- cfg_required(config, "path_lib_istd_neg")
  path_peaktable_istd_neg <- cfg_required(config, "path_peaktable_istd_neg")
  rds_qc_is_neg <- cfg_required(config, "rds_qc_is_neg")
  if (is.null(meta_neg)) stop("run.neg=TRUE but meta_neg is missing")
  if (!file.exists(path_lib_istd_neg)) stop("Negative ISTD library file not found: ", path_lib_istd_neg)
  if (!file.exists(path_peaktable_istd_neg)) stop("Negative ISTD peaktable file not found: ", path_peaktable_istd_neg)
}

wf_ensure_parent_dirs(c(rds_qc_is_pos, rds_qc_is_neg))

```

## Method configuration
```{r}

cat("Method name: ", method_name, "\n")
cat("Internal standard libraries used for QC: \n")
cat(path_lib_istd_pos, "\n")
cat(path_lib_istd_neg, "\n")

```

## Data import
```{r}

peaktable_pos = path_peaktable_istd_pos
peaktable_neg = path_peaktable_istd_neg
    
reference.type <- "reference"

cat("Peaktable istd used for QC are: \n")
if (run.pos) cat(peaktable_pos, "\n")
if (run.neg) cat(peaktable_neg, "\n")
```

## Positive mode

::: panel-tabset
```{r, eval = run.pos}

path_peaktable <- peaktable_pos
path_lib_is <- path_lib_istd_pos

lib.is <- 
  read.csv(path_lib_is, sep = ";", header = TRUE) %>% 
  dplyr::rename(Theoretical.mz = mz,
                Theoretical.rt = rt,
                Formula = formula,
                Ion = adduct) %>% 
  filter(grepl("'", Formula))

peaktable.is <-
  openxlsx::read.xlsx(path_peaktable)
  
features <- 
  peaktable.is[, c("id", "mz", "rt", "identity")] %>% 
  group_by(identity) %>% 
  mutate(n = n(),
         identity_rep = ifelse(n > 1, paste0(identity, "_", row_number()), identity)) %>% 
  ungroup() %>% 
  select(-n)

df_mz <- 
  cbind(features, peaktable.is[, grep("^datafile.*.mz$", colnames(peaktable.is))]) %>% 
  pivot_longer(-c(1:ncol(features)), names_to = "File.name", values_to = "file.mz")
  
df_rt <- 
  cbind(features, peaktable.is[, grep("^datafile.*.rt$", colnames(peaktable.is))]) %>% 
  pivot_longer(-c(1:ncol(features)), names_to = "File.name", values_to = "file.rt")

df_area <- 
  cbind(features, peaktable.is[, grep("^datafile.*.area$", colnames(peaktable.is))]) %>% 
  pivot_longer(-c(1:ncol(features)), names_to = "File.name", values_to = "file.area")  

df_qc <- 
  cbind(df_mz, df_rt[, "file.rt"], df_area[, "file.area"]) %>% 
  mutate(File.name = make.names(gsub("datafile.|.mz$", "", File.name))) %>% 
  left_join(meta_pos %>% mutate(File.name = make.names(File.name)),
            by = "File.name")

# Remove not detected IS
# data.plot <-
#   data.plot[!data.plot$mz == 0, ]

# Combine with theoretical ISTD
combined_file <-
  lib.is %>%
  left_join(df_qc, by= c("name" = "identity")) %>%
  dplyr::rename(ISTD = name) %>% 
  group_by(identity_rep) %>%
  mutate(
    median.rt        = median(file.rt,  na.rm = TRUE),
    median.mz        = median(file.mz, na.rm = TRUE),
    median.intensity = median(file.area, na.rm = TRUE),
    sd.intensity = sd(file.area, na.rm = TRUE),
    RSD.intensity    = sd(file.area, na.rm = TRUE) / mean(file.area, na.rm = TRUE)*100) %>%
  group_by(ISTD, File.name) %>% 
  arrange(desc(median.intensity)) %>% 
  mutate(n = row_number()) %>% 
  filter(n == 1) %>% 
  ungroup() %>% 
  select(-n)

if (reference.type == "reference") {

  combined_file <-
    combined_file %>%
    mutate(
      rt.dev = file.rt - Theoretical.rt,
      mz.dev = (file.mz - Theoretical.mz)/Theoretical.mz*1E6,
      #Intensity.dev = (file.area - median.intensity)/median.intensity*100
      Intensity.dev = (file.area - median.intensity)/sd.intensity
      )

} else if (reference.type == "median") {

  combined_file <-
    combined_file %>%
    mutate(
      rt.dev = file.rt - median.rt,
      mz.dev = (file.mz - median.mz)/median.mz*1E6,
      #Intensity.dev = (file.area - median.intensity)/median.intensity*100
      Intensity.dev = (file.area - median.intensity)/sd.intensity
      )
}

```

```{r evaluation pos, eval = run.pos}

plt <- create_qc(sampled_data = combined_file,
                 figure_height = figure_height,
                 figure_width = figure_width)

summary <- 
  combined_file %>%
  select(ISTD, Theoretical.rt, median.rt, Theoretical.mz, median.mz, median.intensity) %>%
  unique() %>% 
  mutate(rt.diff = median.rt - Theoretical.rt,
         mz.diff = median.mz - Theoretical.mz,
         mz.diff.ppm = (median.mz - Theoretical.mz)/Theoretical.mz*1E6) %>% 
  relocate(rt.diff, .after = median.rt) %>% 
  relocate(c(mz.diff, mz.diff.ppm), .after = median.mz)

qc_is_pos <- list(combined_file = combined_file,
                  plt = plt,
                  summary = summary)

saveRDS(qc_is_pos, file = rds_qc_is_pos)
```

### Overall
```{r ms overall pos, eval = run.pos}

summary %>%
  mutate_if(is.numeric, function(x){round(x, 4)}) %>% 
  dplyr::rename("Internal standard" = "ISTD",            
                "Theoretical RT" = "Theoretical.rt",
                "Median RT" = "median.rt",        
                "RT difference" = "rt.diff",          
                "Theoretical m/z" = "Theoretical.mz",
                "Median m/z" = "median.mz",
                "m/z difference" = "mz.diff", 
                "m/z difference (ppm)" = "mz.diff.ppm",         
                "Median intensity" = "median.intensity") %>% 
  kbl() %>%
  kable_paper()

```

<br>
```{r, eval = run.pos, fig.width = 5, fig.height = 5, out.width = "80%"}
plt[[7]] %>%
  layout(annotations = list(
          list(x = 0,  
               y = 1.0,  
               text = "RSD of internal standards",  
               xref = "paper",  
               yref = "paper",  
               xanchor = "left",  
               yanchor = "bottom",  
               showarrow = FALSE)
        ),
        xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
        yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")) 

```

<br>
```{r, eval = run.pos, fig.width = 5, fig.height = 5, out.width = "80%"}
plt[[8]] %>%
  layout(annotations = list(
          list(x = 0,  
               y = 1.0,  
               text = "Retention time linearity of internal standards",  
               xref = "paper",  
               yref = "paper",  
               xanchor = "left",  
               yanchor = "bottom",  
               showarrow = FALSE)
        ),
        xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
        yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"))

```

### Retention time
```{r ms RT pos, eval = run.pos, fig.height = 5}

plt[[1]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

```{r ms RT pos2, eval = run.pos, fig.height = 5}

plt[[2]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

### m/z
```{r ms m/z pos, eval = run.pos, fig.height = 5}

plt[[3]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

```{r ms m/z pos2, eval = run.pos, fig.height = 5}

plt[[4]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

### Intensity
```{r ms1p Int pos, eval = run.pos, fig.height = 5}

plt[[5]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

```{r ms1p Int pos2, eval = run.pos, fig.height = 5}

plt[[6]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

<br>
<br>
```{r, eval = run.pos}

istd <- unique(combined_file$ISTD)

plt.int <- htmltools::tagList()
for (i in istd) {
  
  data.istd.plot <- 
    combined_file %>% 
    filter(ISTD == i)
  
  if (!is.na(data.istd.plot$median.intensity[1])){
    p <-
      ggplot(data.istd.plot,
             aes(x = Run.order, y = file.area, fill = Sample.type, text = Sample)) +
      geom_col() +
      theme(axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            axis.ticks.x = element_blank()) +
      labs( x = "Run.order",
            y = "Intensity",
            title = i) +
      theme_bw() +
      scale_fill_npg() 
  
    plt.int[[i]] <- as_widget(ggplotly(p))
  }

}

plt.int %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

### Shift
```{r, eval = run.pos, fig.width = 8, fig.height = 5}
p1 <- 
  ggplot(summary) +
    geom_segment( aes(x=ISTD, xend=ISTD, y=0, yend=rt.diff), color="grey") +
    geom_point( aes(x=ISTD, y=0), color = "#F39B7FB2", size=3 ) +
    geom_point( aes(x=ISTD, y=rt.diff), color = "#3C5488B2", size=3 ) +
    coord_flip()+
    scale_x_discrete(limits=rev) +
    theme_bw() +
    xlab("Internal standard") +
    ylab("Difference in retention time")

p2 <- 
  ggplot(summary) +
    geom_segment( aes(x=ISTD, xend=ISTD, y=0, yend=mz.diff.ppm), color="grey") +
    geom_point( aes(x=ISTD, y=0), color= "#F39B7FB2", size=3 ) +
    geom_point( aes(x=ISTD, y=mz.diff.ppm), color= "#3C5488B2", size=3 ) +
    coord_flip()+
    scale_x_discrete(limits=rev) +
    theme_bw() +
    xlab("Internal standard") +
    ylab("Difference in m/z (ppm)")

subplot(p1, p2, nrows = 1, margin = 0.04, titleX = TRUE, titleY = TRUE, shareY = TRUE) 

```
:::

## Negative mode

::: panel-tabset
```{r, eval = run.neg}

path_peaktable <- peaktable_neg
path_lib_is <- path_lib_istd_neg

lib.is <- 
  read.csv(path_lib_is, sep = ";", header = TRUE) %>% 
  dplyr::rename(Theoretical.mz = mz,
                Theoretical.rt = rt,
                Formula = formula,
                Ion = adduct) %>% 
  filter(grepl("'", Formula))

peaktable.is <-
  openxlsx::read.xlsx(path_peaktable)
  
features <- 
  peaktable.is[, c("id", "mz", "rt", "identity")] %>% 
  group_by(identity) %>% 
  mutate(n = n(),
         identity_rep = ifelse(n > 1, paste0(identity, "_", row_number()), identity)) %>% 
  ungroup() %>% 
  select(-n)

df_mz <- 
  cbind(features, peaktable.is[, grep("^datafile.*.mz$", colnames(peaktable.is))]) %>% 
  pivot_longer(-c(1:ncol(features)), names_to = "File.name", values_to = "file.mz")
  
df_rt <- 
  cbind(features, peaktable.is[, grep("^datafile.*.rt$", colnames(peaktable.is))]) %>% 
  pivot_longer(-c(1:ncol(features)), names_to = "File.name", values_to = "file.rt")

df_area <- 
  cbind(features, peaktable.is[, grep("^datafile.*.area$", colnames(peaktable.is))]) %>% 
  pivot_longer(-c(1:ncol(features)), names_to = "File.name", values_to = "file.area")  

df_qc <- 
  cbind(df_mz, df_rt[, "file.rt"], df_area[, "file.area"]) %>% 
  mutate(File.name = make.names(gsub("datafile.|.mz$", "", File.name))) %>% 
  left_join(meta_neg %>% mutate(File.name = make.names(File.name)),
            by = "File.name")
  

# Remove not detected IS
# data.plot <-
#   data.plot[!data.plot$mz == 0, ]

# Combine with theoretical ISTD
combined_file <-
  lib.is %>%
  left_join(df_qc, by= c("name" = "identity")) %>%
  dplyr::rename(ISTD = name) %>% 
  group_by(identity_rep) %>%
  mutate(
    median.rt        = median(file.rt,  na.rm = TRUE),
    median.mz        = median(file.mz, na.rm = TRUE),
    median.intensity = median(file.area, na.rm = TRUE),
    sd.intensity = sd(file.area, na.rm = TRUE),
    RSD.intensity    = sd(file.area, na.rm = TRUE) / mean(file.area, na.rm = TRUE)*100) %>%
  group_by(ISTD, File.name) %>% 
  arrange(desc(median.intensity)) %>% 
  mutate(n = row_number()) %>% 
  filter(n == 1) %>% 
  ungroup() %>% 
  select(-n)

if (reference.type == "reference") {

  combined_file <-
    combined_file %>%
    mutate(
      rt.dev = file.rt - Theoretical.rt,
      mz.dev = (file.mz - Theoretical.mz)/Theoretical.mz*1E6,
      #Intensity.dev = (file.area - median.intensity)/median.intensity*100
      Intensity.dev = (file.area - median.intensity)/sd.intensity
      )

} else if (reference.type == "median") {

  combined_file <-
    combined_file %>%
    mutate(
      rt.dev = file.rt - median.rt,
      mz.dev = (file.mz - median.mz)/median.mz*1E6,
      #Intensity.dev = (file.area - median.intensity)/median.intensity*100
      Intensity.dev = (file.area - median.intensity)/sd.intensity
      )
}


```

```{r evaluation neg, eval = run.neg}

plt <- create_qc(sampled_data = combined_file,
                 figure_height = figure_height,
                 figure_width = figure_width)

summary <- 
  combined_file %>%
  select(ISTD, Theoretical.rt, median.rt, Theoretical.mz, median.mz, median.intensity) %>%
  unique() %>% 
  mutate(rt.diff = median.rt - Theoretical.rt,
         mz.diff = median.mz - Theoretical.mz,
         mz.diff.ppm = (median.mz - Theoretical.mz)/Theoretical.mz*1E6) %>% 
  relocate(rt.diff, .after = median.rt) %>% 
  relocate(c(mz.diff, mz.diff.ppm), .after = median.mz)

qc_is_neg <- list(combined_file = combined_file,
                  plt = plt,
                  summary = summary)

saveRDS(qc_is_neg, file = rds_qc_is_neg)
```

### Overall
```{r ms overall neg, eval = run.neg}

summary %>%
  mutate_if(is.numeric, function(x){round(x, 4)}) %>% 
  dplyr::rename("Internal standard" = "ISTD",            
                "Theoretical RT" = "Theoretical.rt",
                "Median RT" = "median.rt",        
                "RT difference" = "rt.diff",          
                "Theoretical m/z" = "Theoretical.mz",
                "Median m/z" = "median.mz",
                "m/z difference" = "mz.diff",    
                "m/z difference (ppm)" = "mz.diff.ppm",      
                "Median intensity" = "median.intensity") %>% 
  kbl() %>%
  kable_paper()

```

<br>
```{r, eval = run.neg, fig.width = 5, fig.height = 5, out.width = "80%"}
plt[[7]] %>%
  layout(annotations = list(
          list(x = 0,  
               y = 1.0,  
               text = "RSD of internal standards",  
               xref = "paper",  
               yref = "paper",  
               xanchor = "left",  
               yanchor = "bottom",  
               showarrow = FALSE)
        ),
        xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
        yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"))

```

<br>
```{r, eval = run.neg, fig.width = 5, fig.height = 5, out.width = "80%"}
plt[[8]] %>%
  layout(annotations = list(
          list(x = 0,  
               y = 1.0,  
               text = "Retention time linearity of internal standards",  
               xref = "paper",  
               yref = "paper",  
               xanchor = "left",  
               yanchor = "bottom",  
               showarrow = FALSE)
        ),
        xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
        yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"))

```

### Retention time
```{r ms RT neg, eval = run.neg, fig.height = 5}

plt[[1]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

```{r ms RT neg2, eval = run.neg, fig.height = 5}

plt[[2]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

### m/z
```{r ms m/z neg, eval = run.neg, fig.height = 5}

plt[[3]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

```{r ms m/z neg2, eval = run.neg, fig.height = 5}

plt[[4]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

### Intensity
```{r ms1p Int neg, eval = run.neg, fig.height = 5}

plt[[5]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

```{r ms1p Int neg2, eval = run.neg, fig.height = 5}

plt[[6]] %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

<br>
<br>
```{r, eval = run.neg}

istd <- unique(combined_file$ISTD)

plt.int <- htmltools::tagList()
for (i in istd) {
  
  data.istd.plot <- 
    combined_file %>% 
    filter(ISTD == i)
  
  if (!is.na(data.istd.plot$median.intensity[1])){
    p <-
      ggplot(data.istd.plot,
             aes(x = Run.order, y = file.area, fill = Sample.type, text = Sample)) +
      geom_col() +
      theme(axis.title.x = element_blank(),
            axis.text.x = element_blank(),
            axis.ticks.x = element_blank()) +
      labs( x = "Run.order",
            y = "Intensity",
            title = i) +
      theme_bw() +
      scale_fill_npg() 
  
    plt.int[[i]] <- as_widget(ggplotly(p))
  }

}

plt.int %>%
  layout(
    xaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all"),
    yaxis = list(showline = TRUE, linewidth = 1, linecolor = '#999999', mirror = "all")
  )

```

### Shift
```{r, eval = run.neg, fig.width = 8, fig.height = 5}
p1 <- 
  ggplot(summary) +
    geom_segment( aes(x=ISTD, xend=ISTD, y=0, yend=rt.diff), color="grey") +
    geom_point( aes(x=ISTD, y=0), color = "#F39B7FB2", size=3 ) +
    geom_point( aes(x=ISTD, y=rt.diff), color = "#3C5488B2", size=3 ) +
    coord_flip()+
    scale_x_discrete(limits=rev) +
    theme_bw() +
    xlab("Internal standard") +
    ylab("Difference in retention time")

p2 <- 
  ggplot(summary) +
    geom_segment( aes(x=ISTD, xend=ISTD, y=0, yend=mz.diff.ppm), color="grey") +
    geom_point( aes(x=ISTD, y=0), color= "#F39B7FB2", size=3 ) +
    geom_point( aes(x=ISTD, y=mz.diff.ppm), color= "#3C5488B2", size=3 ) +
    coord_flip()+
    scale_x_discrete(limits=rev) +
    theme_bw() +
    xlab("Internal standard") +
    ylab("Difference in m/z (ppm)")

subplot(p1, p2, nrows = 1, margin = 0.04, titleX = TRUE, titleY = TRUE, shareY = TRUE)

```
:::

```{r session info, include = FALSE, eval = FALSE}

# Session info

utils::sessionInfo()

```